growgroup/gg-styleguide

app/assets/scss/object/components/_forms.scss, app/assets/scss/object/components/_grid.scss, app/assets/scss/object/components/_slidebar.scss, app/inc/mixins/_anchor.pug, app/inc/mixins/_slidebar.pug
-  WP化した際に、ラジオボタン・チェックボタンのlast-childが効いていないので、last-of-typeに変更
※WPではinput type="hidden"の要素が追加で入るので、狙った要素がlast-childになっていないため
- largeとmediumのscssの記述順を変更
※ .large-4.medium-6.small-12 という記述で３段階のレスポンシブ対応ができるようにするため
- コメントアウトがhtmlに出力されていたので修正
- コンパイル時にでる You should not have pug tags with multiple attributes. を出ないように修正
- .c-slidebar-buttonをaタグからbuttonタグに変更
※ ページ遷移を伴わないボタンは button type="button" にできればしたいため
=> formとgridのscss調整、slidebarの開閉ボタンをbuttonタグへ、anchor.pugのコメントと警告を出ないようにする

app/assets/scss/layout/_post-content.scss, app/assets/scss/object/components/_list.scss, app/assets/scss/object/components/_toc.scss, app/assets/scss/object/utility/_margin.scss, app/format/components/_text.pug
`&.is-xs` が２回出てきていたので、不要そうな２回目の `&.is-xs` を削除
`ol`の中に`ul`を入れても、スタイルが正しく当たるように調整（最後にスクショを添付しました）
_post-content.scssの修正の影響を受けている箇所を調整
`ol.c-list.is-outline` の中のリストが `ol` ではなく `ul` になっていたので、  
今までの見かけ通りの`ol`に修正
=> _margin.scss不要な箇所削除、olの中にulを入れてもスタイルが正しく当たるよう調整

app/assets/js/app/anchor.js
27行目にヘッダーのclass名を記入すると、
自動でアンカーリンクの位置がヘッダーの高さ分だけずれるようにしました。
↓使用例
```
var defaultOptions = {
selector: '.js-anchor',
dataSelector: 'anchor-target',
scrollSpeed: 300,
easing: 'linear',
headerElement:'.l-header' // ヘッダーの高さ分ずらしたいとき '.l-header' のように
};
```
100行目からあとに記載した部分。
1. URLに#がついているか確認
2. defaultOptionsにheaderElementの指定があるか確認
3. window.onload のタイミングで、ヘッダーの高さをはかる・#のついている要素の位置を測る
4. 表示位置をずらす
というようなことをさせています。
=> anchor.js ヘッダーの高さ分アンカーの位置をずらすためのオプション追加

app/assets/scss/object/components/_slidebar.scss, app/inc/layout/_header.pug, app/inc/mixins/_slidebar.pug
下記を行いました。
- 何とも競合していない部分の!importantを消す
- !importat なしでも負けないように詳細度を上げ下げする
この部分の余白がない案件が多そうかな？と考えて、余白を消しました。
　※ こちらは必要そうであれば戻します！
=> _slidebar.scss importantなしで機能するように、など微調整

app/assets/js/app/gsap.js
gsap.jsが、使われていないページ（targetに設定した要素が存在しないページ）で
下記スクショの通りtarget not foundを出しているのを止めました。
参考にしたもの：
https://greensock.com/forums/topic/22491-gsap3-target-object-not-found/
```
//this.animate = this.animate;
```
のコメントを解除して
app.js　から　this.gsap.animate　を呼び出すと下記のスクショのエラーが出たので、
エラーが出ないようにしました。
参考にしたもの：
https://mebee.info/2020/10/12/post-20168/
=> gsapがconsoleに target not found を出すのを止める

app/assets/scss/object/components/_forms.scss, app/contact/confirm/index.pug, app/contact/index.pug
フォームの入力・確認画面のボタンを
WordPress実装時に同じひとつのdivに入れるだけで機能するように、
マークアップとCSSを変更しました。
```
<div class="c-forms__submit">
[mwform_bconfirm class="c-button is-xlg" value="confirm"]確認画面へ[/mwform_bconfirm]
[mwform_bback class="c-button c-forms__submit__back is-lg is-secondary is-arrow-left" value="back"]戻る[/mwform_bback]
[mwform_bsubmit name="submit" class="c-button c-forms__submit__submit is-lg" value="send"]送信する[/mwform_bsubmit]
</div>
```
=> MW WP Form用にc_forms__submitのボタンのマークアップを書き換え

app/assets/scss/object/components/_news.scss, app/assets/scss/object/components/_post-navs.scss
テキストの長さによってはレイアウトが崩れるのを修正しました
主に「一覧を見る」ボタンに対してposition を使わないようにする対応をしました。
あわせて微妙な横幅のときのレイアウトも調整しています。
=> c-news , c-post-navsのスタイルの微調整

webpack.config.babel.js
app.js の slick-slider.jsが読み込む slick-theme.css が使っているフォント系のファイルが
正しく出力されていない問題を修正しました。
=> dist直下に変なファイルができるのを修正

app/assets/scss/object/components/_form-head.scss, app/assets/scss/object/components/_pagination.scss, app/contact/complete/index.pug, app/contact/confirm/index.pug, app/contact/index.pug, app/news/index.pug
ページネーション系と、お問合せフォーム系に以下の変更を加えました。
/news/index.pugで　+c_pagination() を使うようにしてみました。
（class追加している左寄せの方は直書きのままです…）
.c-pagination ul に flex-wrap:wrap を追加
.c-pagination ul li にmargin-bottomを追加（折り返した場合にくっつかないように）
これで、スマホでも突き抜けません！
▼改善事項DB
https://www.notion.so/growgroup/pagination-0ba2bbeda6824c169d2341f3ec8702d5
page-headerがないことが多く、h1紛失がちだったのでデフォルトをh1にしてみました。
▼改善事項DB
https://www.notion.so/growgroup/gg-styleguide-c-form-head__title-h1-36a20e0bd51e4f62bf1eaf973fb794be
- /contact/index.pug に、confirmとcompleteの調整が必要な旨のコメント追加
- それに伴い、 /confirm/と/complete/のl-sectionにつけている背景色classを
/contact/と同じにしてみました（同じにして大丈夫だったでしょうか…）
- formタグを削除して、クライアント確認時ページ遷移されないようにする
=> ページネーション系・お問合せフォーム系

app/assets/scss/foundation/_normalize.scss
こちらの件です。
https://www.notion.so/growgroup/af0da5c508e74d12850353b952f04868
案件にてiOSで細部のギザギザが気になり修正したため、
そのコードをこちらに展開します…！
` /! autoprefixer: ignore next */ ` をつけないと、
AutoprefixerにCSSハックを殺されました。
=> image-rendering: -webkit-optimize-contrast; の入れ方調整

package.json, webpack.config.babel.js, webpack.style.config.babel.js
→ cpxがかかったタイミングでなぜかnpmが固まる（？）のを回避
→ ファイル拡張子ではなく、フォルダ単位でコピーするようになったことに注意
→ app.jsでimportしてるので、scripts.jsのファイル実体は不要のため
　webpack.style.config.babel.jsだけにする
→ npm start 中にscssを書き換えたとき、反映が遅い問題を解決
★ただし、npm start中に追加されたscssファイルはウォッチ対象外。
package.jsonに以下を追加すると直るが、**macでしか動かないので今回のプルリクでは除外**
```
"develop:css-chokidar": "chokidar 'app/assets/**/*.scss' -c \"if [ '{event}' = 'add' ];then npm run develop:css; fi;\"",
```
　
=> npm,webpackの動作を変更（cpxをやめてwebpackにする、scssのコンパイルの走り方をかえるなど）

.markuplintrc, package-lock.json, package.json
`npm run build` のあと
`npm run lint:html` すると
dist内の全てのhtmlファイルに対して自動でHTML構文チェックがかかります
=> markuplint ( lint:html ) を追加

webpack.config.babel.js
app/assets/fonts が dist/assets/fonts にコピーされるように
webpack.config.babel.js を変更
=> assets/fonts がデフォルトで dist にコピーされるようにする

app/assets/js/app.js, app/assets/scss/layout/_footer.scss, app/assets/scss/layout/_offer.scss, app/assets/scss/layout/_post-content.scss, app/assets/scss/object/components/_accordion.scss, app/assets/scss/object/components/_banners.scss, app/assets/scss/object/components/_blockquote.scss, app/assets/scss/object/components/_box-archive.scss, app/assets/scss/object/components/_buttons.scss, app/assets/scss/object/components/_hero-block-line.scss, app/assets/scss/object/components/_list.scss, app/assets/scss/object/components/_menu-list.scss, app/assets/scss/object/components/_news-lg.scss, app/assets/scss/object/components/_pagetop.scss, app/assets/scss/object/components/_slidebar.scss, app/assets/scss/object/components/_tabs.scss, app/assets/scss/object/project/_post-item.scss, app/assets/scss/object/utility/_text.scss, app/inc/foundation/_head.pug, package-lock.json, package.json
以下の3点を行いました
- webfont.js を利用したGoogle Fonts 等のフォント読み込みのscriptタグを削除
- _head.pug
- fontsource を用いたGoogle Fonts（とMaterial Icons）の読み込みコードを追加
- package.json
- app.js
- gg-styleguide内で標準で利用している Material Icons が2種あったため、1種類に変更
- 各種scssファイル
使用方法についての説明は以下
https://www.notion.so/growgroup/Web-90cc36baf41b4ba18b9d04dc1a2311c5
=> webfont.js 廃止・fontsource でのGoogleFonts読み込みのコードに変更

app/assets/js/app.js, app/assets/scss/foundation/_normalize.scss, app/assets/scss/foundation/_settings.scss, app/assets/scss/object/utility/_text.scss
[body.en を追加したコミット](https://github.com/growgroup/gg-styleguide/commit/95b559a533700a9aa147b79e2b380756d7673b4e)の内容に対して以下を行いました。
npm start 時に以下の警告が出ていたのと、
`Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.`
もとの値（font-size: 0.85em;）から変更していなければ英語版で指定しなくても良い気がしたので、
削除して、_text.scssの方に必要に応じて指定するのが伝わるといいな…というお気持ちのコメントアウトを作成
スマホのときのフォントサイズもとりあえず日本語と同じ指定方法にとりあえず統一。
line-heightの指定も日本語の方と同様に計算式ではなくて数値で指定に統一。
案件で使わないfontはapp.jsからコメントアウトする想定だが、
robotoは消してほしくないのでそれがわかるようにコメントを追加
=> body.en のときのfont-size指定の調整、robotoについてのコメント追加

app/assets/scss/foundation/_mixin.scss, app/assets/scss/foundation/_normalize.scss, app/assets/scss/object/components/_breadcrumb.scss, app/assets/scss/object/components/_heading.scss, app/assets/scss/object/components/_label.scss, app/assets/scss/object/components/_pagination.scss
以下を行いました。
- $font-base-letter-spacing をCSS変数に入れて各要素に効くようにする
- font-formatでもletter-spacingを省けるように
```
:root{
--spacing:0.05em;/*実際には $font-base-letter-spacing が入る*/
}
*{
letter-spacing: var(--spacing);
}
```
これで、font-size 変更するたびに letter-spacingを指定する必要はなくなる。
参考：https://deep-space.blue/web/2240
```
.hoge{
--spacing:0.1em;
}
```
これで、.hoge も .hoge .fuga も全部letter-spacing:0.1em になる。
```
.fuga{
letter-spacing:0.1em;
}
```
これの場合 .fuga は letter-spacing:0.1em、
.fuga .piyo はletter-spacing:0.05emという感じになる（はず）
font-formatでもletter-spacingを省けるようにしました。
SCSS
```
@include font-format(14,null,20,normal);
```
CSS
```
font-size: 0.875rem;
line-height: 1.4285714286;
font-weight: normal;
```
ついでに以下も実施。
SCSS
```
@include font-format(14,null,20);
```
CSS
```
font-size: 0.875rem;
line-height: 1.4285714286;
```
=> $font-base-letter-spacing が各要素に正しく（見かけ上正しく）効くようにする

webpack.config.babel.js
PDFやMP4などimagesに入れないようなファイルを入れるためのディレクトリの準備をしました。
- app/assets/files ディレクトリを新規作成
- webpack.config.babel.jsへ「appからdistにコピーする」の設定追記
=> filesディレクトリの追加とdistへのコピー設定

app/assets/js/app/accordion.js
もともとの処理だとfind()で.js-accordion内のすべての「data-accordion-content」がついている要素を
target.content として判定し
アコーディオンを入れ子にすると内側のアコーディオンも連動して動いてしまっていた
```
target.title = target.find('*[' + this.options.titleTargetAttr + ']');
target.content = target.find('*[' + this.options.contentTargetAttr + ']');
```
`eq(0)` を使い、find() でとってきた要素の1番目だけを変数に入れるように変更。
```
target.title = target.find('*[' + this.options.titleTargetAttr + ']').eq(0);
target.content = target.find('*[' + this.options.contentTargetAttr + ']').eq(0);
```
これで仮に以下のような構造になっていても、
.js-accordionごとに最初に出てくるdata-accordion-contentだけが展開するようになる
```
+e.block.js-accordion
+e.head(data-accordion-title="accordion-title")
+e.content(data-accordion-content="accordion--text")
+e.block.js-accordion
+e.head(data-accordion-title="accordion-title") …
```
=> .js-accordionが、アコーディオンinアコーディオンに耐えられる用に調整

app/assets/js/app/custom.js, app/assets/scss/layout/_searchform.scss, app/assets/scss/object/components/_slidebar.scss, app/inc/layout/_header.pug, app/inc/mixins/_mixins.pug, app/inc/mixins/_searchform.pug, app/inc/mixins/_slidebar.pug
mixin化しています。（mixins/_searchform.pug）
関数名を searchFormModal() 関数に変更して、
閉じる処理を「フォーム本体以外をクリックしたら閉じる」に変更しました。
HTMLやCSSの構成をちょっと変えています。
- アコーディオン in アコーディオンの実装例として孫階層まで追加しました
- 2階層目のデザインをデザインフォーマットXDに似せました
- CSSのスタイリングを（個人的に）やりやすいようにクラス命名を調整しました。
- 使いにくそうでしたら直しますのでご指摘ください！
- もういらなそうな-webkitベンダープレフィックスを消しました
- ヘッダーの高さにまつわる数値を `$slidebar-header-height` に設定して一括変更できるようにしました
=> サイト内検索フォームのコンポーネント全体的に変更、slidebarの孫階層追加とCSS整理

webpack.config.babel.js
CopyPluginの設定に、以下の記述を追加しました。
```
//robots.txtは、そのままコピーする
{
from: path.resolve(__dirname, 'app/robots.txt'),
to: path.resolve(__dirname, 'dist/'),
},
```
dist 直下に、robots.txt が生成されるようになります。
=> /app/robots.txt を /dist/ にコピーする設定の追加

app/assets/scss/foundation/_mixin.scss
WP工程時にHTML構造が変わったときに困る認識でしたが、
よく見たら
.c-buttonは全部 letter-spacing:0.1em にしたいが、
.c-button span の方はletter-spacing:var(--letter-spacing)なので、実際表示は0.06em
というような事故も発生していたので修正プルリクです…！
CSS変数導入時にこちら直していなくてすみません…！
=> font-format() : letter-spacingの出力を --letter-spacingに変更

app/assets/scss/foundation/_forms.scss, app/assets/scss/foundation/_mixin.scss, app/assets/scss/object/components/_accordion-list.scss, app/assets/scss/object/components/_grid.scss, app/assets/scss/object/project/_owl-carousel.scss, app/assets/scss/object/utility/_animate.scss, package-lock.json, package.json, postcss.config.js
Autoprefixerの設定を調整し、ビルド時に表示されていた各種警告が出ないようにしました。
また、Autoprefixerがあれば不要になる、手書きベンダープレフィックスをある程度除去しました。
▼該当改善事項
https://www.notion.so/growgroup/autoprefixer-IE11-389247dce3a74b2eaf158755b8f7aa95
```
"browserslist": [
"last 3 versions",
"not dead",
"iOS >= 14",
"Safari >= 14"
],
```
※ブラウザ設定が正しく効いているか若干不安だが、
`backdrop-filter` に必要なベンダープレフィックスがつくのは確認済み
`caniuse-lite is outdated` の出力を消すため。
build時に `caniuse-lite is outdated` がでなければ成功。
中央寄せ手法として以下を使っても、警告が出ないことを確認済み。
```
display: grid;
place-items: center;
```
_normalize.scss と _owl-carousel.scss以外のscssについて、
手書きのベンダープレフィックスを除去して見通しをよく。
foundation/_forms.scss の ::placeholder について、
なぜかベンダープレフィックス系ではないものについては
:placeholder_shownの色を変えていたので
::placeholder に統一。
=> [update] autoprefixser 

app/assets/scss/foundation/_mixin.scss, app/assets/scss/object/components/_heading.scss, app/assets/scss/object/components/_pagination.scss
元の記述のままでも動きますが、
呼び出すときに""での出力スキップが可能になりました。
```
@include font-format(14,null,20,normal);
```
```
@include font-format(14, "", 20, normal);
```
出力されるCSSは一緒です。
```
line-height: math.div($height, $size) * 1;
```
```
line-height: calc($height / $size);
```
コメントアウトの記述を間違えていたので直しました。
=> [update] font-format & font-format-light : CSSスキップをnullではなく"" で可能に

app/archive-twocolumns/index.pug, app/archive-twocolumns/page/index.pug, app/contact/complete/index.pug, app/contact/confirm/index.pug, app/contact/index.pug, app/format/index.pug, app/news/category/index.pug, app/news/category/page/index.pug, app/news/index.pug, app/page/index.pug, app/result/index.pug, app/sitemap/index.pug, app/twocolumns/index.pug
ページ内で定義したconfig.idやconfig.titleと同じ文字列を使う箇所は
あらかじめ同じ文字列が自動で入るように変更しました。
**違う文字列を入れたいページでは、${current.id}等の記述を消して普通に文字を入れて使えます。**
```
block append config
- current.id = "format" // ページのID
- current.title = "フォーマット" // タイトル
- current.description = "これはフォーマットページの説明文です" // 説明文
- current.bodyClass = "format" // body に付与するクラス
- current.path = "/format/" // ページのpath
- current.depth = 2 // ページの階層
```
```
block append config
- current.id = "format" // ページのID
- current.title = "フォーマット" // タイトル
- current.description = `これは${current.title}についての説明文です` // 説明文
- current.bodyClass = `${current.id}` // body に付与するクラス
- current.path = `/${current.id}/` // ページのpath
- current.depth = 2 // ページの階層
```
```
- current.path = `/contact/${current.id}/` // ページのpath
```
=> [update] block append config : 各ページでid、titleと同じ文字列を入れる箇所に自動で文字が入るように

app/inc/mixins/_breadcrumb.pug
▼改善事項
https://www.notion.so/growgroup/mixin-c_breadcrumb-if-b3f4b15385354a588038168bb54f6653
改善事項で提案した再帰的な処理だと、各ページ側の記述方法も変更しないといけなくて大がかりなので、
いったん現状の引数のままでコードの重複だけ減らしました。
▼呼び出し（変更なし）
```
+c_breadcrumb("2階層目","2","3階層目","3")
+c_breadcrumb("2階層目","2")
+c_breadcrumb()
```
▼出力（変更なし）
=> [update] c-breadcrumb : if分岐を調整してコードの重複を減らす

app/assets/js/app.js, app/assets/scss/foundation/_webfont.scss, package-lock.json, package.json
▼該当改善事項
https://www.notion.so/growgroup/fontsource-material-icons-rounded-fontsource-material-icons-round-b47b94494c2b4262abf50f5c4f032db4
最新のMaterial Icons では Rounded は material-icons-round だが、
gg-styleguideはmaterial-icons-rounded だったので
- Fontsourceの最新版に差し替え v4 → v5
- Fontsourceの最新版 v5 だと .material-icons のようなclass名がCSSから消えるため、
webfont.scssにいったん記載して元通りの動作になるように調整
を行いました。
フォントファミリーの呼び出し名が変わって最新のCDNと同じになります
https://fonts.googleapis.com/css2?family=Material+Icons+Round
```
font-family: 'Material Icons Rounded'
```
```
font-family: 'Material Icons Round';
```
=> [update] app.js : material-iconsの各種読み込みアップデート

app/assets/scss/foundation/_mqpacker.scss, app/assets/scss/style.scss, package-lock.json, package.json, webpack.style.config.babel.js
▼改善事項
https://www.notion.so/growgroup/https-github-com-shoonia-css-mqpacker-webpack-plugin-CSS-c692ed1c5591474485bb2d848b2baf9d
▼導入したもの
https://github.com/shoonia/css-mqpacker-webpack-plugin
---
https://github.com/shoonia/css-mqpacker-webpack-plugin を使ってメディアクエリの最終出力をまとめます。
CSSの行数が減る＝ファイルサイズが減ります。
- webpack.style.config.babel.jsにて、css-mqpacker-webpack-plugin を実行しています
- 出力されるメディアクエリの順番は、CSS全体の中での出現順になります
- CSS出現順序を制御するため、foundation/_mqpacke.scss に主要なメディアクエリを記載してあります（PC→TB→SPの順で）
こちらの追加・順番変更で対応できます。
「ここだけまとめないでほしい」みたいなのはできないので、
まとまると困るようだったら以下の方法で処理を切りましょう。
optimization の部分を全体的にコメントアウト
または、optimization内 minimize をfalseにしてください。
`@import "foundation/_mqpacker";` をコメントアウトすると、無駄なゴミが出なくてよいです。
=> [add] css-mqpacker-webpack-plugin : webpackでCSSのメディアクエリ出力をまとめる

app/assets/scss/foundation/_mqpacker.scss
https://github.com/growgroup/gg-styleguide/pull/88 の修正
[_container.scss](https://github.com/growgroup/gg-styleguide/blob/master/app/assets/scss/layout/_container.scss) に直接 `@media` が書いてあるのでその分を追加しました。
=> _mqpacker.scss に記載するメディアクエリの追加

app/assets/js/app.js, app/assets/scss/font.scss, webpack.config.babel.js
▼改善事項
https://www.notion.so/growgroup/Material-icon-f926f64b2e8a456fa4636663ac337309
---
▼マニュアル更新済み
https://www.notion.so/growgroup/Web-90cc36baf41b4ba18b9d04dc1a2311c5?pvs=4#3a4483f8b6fd44d0b0759a88d92b7571
---
fontsourceの[Faces Mixin](https://fontsource.org/docs/getting-started/faces-mixin)を利用して、Material Iconsのfont-displayの値を変更できるようにしました。
出力例
```
/* material-icons-outlined-latin-400-normal */
@font-face {
font-family: "Material Icons Outlined";
font-style: normal;
font-display: block;
font-weight: 400;
src: url(../../assets/fonts/material-icons-outlined-latin-400-normal.woff2) format("woff2"), url(../../assets/fonts/material-icons-outlined-latin-400-normal.woff) format("woff");
}
```
- Material Iconsの読み込みはfont.scssで行うようにしました（app.jsでの読み込みではFaces Mixinが使えないため）
- それに伴いapp.jsからMaterial …
=> [update] material-icons : font-displayの値を変更できるように

app/assets/js/app/anchor.js
anchor.jsを用いたアンカーリンクのスクロール時、
正常にフォーカスが移動していない問題を修正しました。
改善事項
https://www.notion.so/growgroup/anchor-js-0a1e4369a8b745aba9f99f8b9a5c145d
anchor.jsを用いたアンカーリンクをキーボード操作で利用する際、以下の問題があった。
enterでアンカーリンクを操作した後、
次にtabキーを使用すると、アンカーの位置の次では無く
アンカーリンクボタンの次にフォーカスが当たる。（スクロール位置が元に戻る）
[smooth-scroll.js](https://github.com/cferdinandi/smooth-scroll/blob/master/src/core.js#L318-L325) を参考に
anchorTargetに対して一時的にtabindexを設定して、フォーカスをanchorTargetへ移動する動作を追加しています。
=> [update] anchor.js : アンカークリック時のフォーカスの移動

package-lock.json, package.json, postcss.config.js
2を解決しようとしたら、1も直さざるを得なかったので同時に直しました。
▼該当改善事項
https://www.notion.so/growgroup/prepend-selector-postcss-postcss-plugin-was-deprecated-22a309c47e5941069a36e7ae0413db60
> prepend-selector-postcss: postcss.plugin was deprecated. Migration guide:
> https://evilmartians.com/chronicles/postcss-8-plugin-migration
プラグインを少し新しいpostcss-prefix-selectorに変更する。
▼該当改善事項
https://www.notion.so/growgroup/admin-style-css-letter-spacing-body-line-height-dcb831fe106d48afbce9405e6fd278b7
`:root` を変換対象から省きました。
ついでに bodyとhtmlの変換はともに #growp-editor-wrapper にしました
（元は　body #growp-editor-wrapper のように出ていたと思う）
修正後
修正前
=> [update] postcss : admin-style.cssの処理変更

app/assets/js/app/anchor.js
▼対象改善事項
https://www.notion.so/growgroup/anchor-js-outline-css-Safari-outline-smooth-scroll-js-431fef62b50f4f84a3680556593315b2
▼関連プルリクエスト
https://github.com/growgroup/gg-styleguide/pull/97
https://github.com/growgroup/gg-styleguide/pull/97 で対応した anchor.jsのフォーカス位置調整で
Safari（Mac OS）の場合にフォーカスインジケーターが表示されてしまっていた問題の修正。
[smooth-scroll.js](https://github.com/cferdinandi/smooth-scroll/blob/master/src/core.js#L318-L325) を参考に
スクロール位置移動後も `outline:none` のスタイルを削除しないようにしました。
=> [update] anchor.js Safariでのフォーカス修正

app/assets/js/app/slidebar.js, app/inc/mixins/_slidebar.pug
▼関連改善事項
https://www.notion.so/growgroup/voice-over-slidebar-53fc0d8e25254637aca07b7d2694b899
slidebarが閉じた状態でも、
（スマホ幅のときに）tabキーでの操作またはiOSのVoiceOverでメニューにフォーカスが当たる問題の改善。
1. slidebarの初期状態にinert属性を付与
2. slidebarの開閉操作でinert属性をつけ外し
3. iOSのVoiceOverだとフォーカス中の要素の直前・直後の要素のinert属性の有無の変更を検知できていない気がするので
フォーカス位置を開閉操作に合わせて移動
`inert` は本来 `<div inert>` という形で付与するのが通例のはずだが、
pugやjQueryで値無しの指定方法が分からなかった。
iOS 15.5以上。
=> [update] slidebar : メニューが閉じた状態でもtabでの操作やvoiceoverでのフォーカスが当たる問題の改善

app/inc/foundation/_head.pug
WordPress 6.4でjQueryが3.7.1になる件の反映
https://core.trac.wordpress.org/ticket/59227
▼関連改善事項
https://www.notion.so/growgroup/WordPress6-3-jQuery-3-7-7378b5133dc1478fb7b8fc755653a359
=> [update] jQuery : 3.6.3 → 3.7.1

app/inc/mixins/_cssrules.pug, build/pug.js
▼対象改善事項
https://www.notion.so/growgroup/l-pug-js-addComponentFile-ee9f7c88672046519de91b5eb5785e69
`+l.hoge`したときのscssファイル生成の修正。
- pug.js に記載のscssファイル生成処理が.c-hoge 専用だったため、.l-hoge の場合に期待される動作を追加
- `+l`のmixin側で呼び出している関数を↑↑で追加したものに変更
- `+l.hoge` で /layout/にscssファイルが生成されるか
- `+l.offer` 等、すでにscssがあるときは新規のファイル生成が起こらないか
- `+c.hoge` で/component/にscssファイルが生成されるか
=> [update] cssrules, pug.js:  `+l.hoge`したときのscssファイル生成の修正

app/assets/scss/foundation/_normalize.scss
▼関連改善事項
https://www.notion.so/growgroup/normalize-css-beb73ea1e88f42d28166a1ac268fa579
normalize.scssが nomalize.cssに追記しまくったものになっておりそのまま置き換えができないため、
歴史的背景として消してはダメなものが消えていたら教えてください。
元：8年くらい前のもの
https://github.com/necolas/normalize.css/blob/3.0.3/normalize.css
↓
最新：5年くらい前のもの
https://github.com/necolas/normalize.css/blob/8.0.1/normalize.css
例えば以下のような部分
```
/**
* Render the `main` element consistently in IE.
*/
main {
display: block;
}
```
WordPress実装時に以下のようなCSSがブロックエディタ内のCSSを打ち消しすぎることを防ぐ
```
#growp-editor-wrapper article,#growp-editor-wrapper aside,#growp-editor-wrapper details,#growp-editor-wrapper figcaption,#growp-editor-wrapper figure,#growp-editor-wrapper footer,#growp-editor-wrapper header,#growp-editor-wrapper hgroup,#growp-editor-wrapper main,#growp-editor-wrapper …
```
=> [update] normalize.scss : 3.0.3ベースのものを8.0.1ベースに調整 + IE用の記述を除去

app/assets/js/app/slidebar.js, app/assets/js/scripts.js
https://www.notion.so/growgroup/PC-b40130adbaf14fecb93acf551b0e0499
スマホメニューを開いた後、PC表示に戻すとスクロールできない
=> slidebarリサイズ時にスクロールできない原因を解決

app/assets/scss/foundation/_mixin.scss, app/assets/scss/foundation/_normalize.scss, app/assets/scss/foundation/_settings.scss
▼関連改善事項
https://www.notion.so/growgroup/HTML-e6286b77fb4f424e85c0296f9a885457
本文フォントサイズが16px以外の案件で、以下を変更すると`<html>`タグのfont-sizeが変更になるが
`$font-base-size: 16px !default; // body のフォントサイズ`
WordPress組み込み後にブロックエディタ（非iframe）の管理画面上では
`<html>`タグのfont-sizeが16pxのままとなり、サイズの計算がおかしくなる問題
以下の部分を変更しても、`<html>`タグのfont-sizeが変更にならないようにする
`$font-base-size: 16px !default; // body のフォントサイズ`
追加した `$font-html-size` については値を変更しないでください。
この変数は `rem-calc()` のmixinでの計算式にも利用しています。
`$font-base-size` を利用しているmixinに `row-limit()` がありましたが、
`line-clamp()`の登場で`row-limit`の利用は非推奨になっていましたので削除しました。
=> $font-html-size の追加＋関連mixinの整理

app/blocks/index.pug, app/contact/complete/index.pug, app/contact/confirm/index.pug, app/contact/index.pug, app/download/index.pug, app/download/page/index.pug, app/format/index.pug, app/inc/foundation/_base.pug, app/index.pug, app/news/category/index.pug, app/news/category/page/index.pug, app/news/index.pug, app/page/index.pug, app/result/index.pug, app/sitemap/index.pug
▼関連改善事項
https://www.notion.so/growgroup/l-main-base-e44d3968fefa438bb8a5b4f31d61d568
l-mainからメインコンテンツが意図せず飛び出すことがないようにbaseごと工夫したい
1カラムレイアウト用のpugについても、_base.pug側に .l-main を設置するように変更しました。
=> [update] _base.pug : main.l-mainを各ページではなく base.pug 側で書くように変更

app/assets/scss/object/components/_buttons.scss, app/inc/layout/_footer.pug
▼関連改善事項
https://www.notion.so/c-button-outline-none-002e4733baf843678e2938cee2788d18
https://www.notion.so/growgroup/pagetop-aria-label-96a3c410241540d2b7fb7b6cd9161ed5
参考: https://blog.studio.design/ja/posts/outline0
キーボードフォーカスが当たるようにするため
アイコンしかないaタグに意味のあるアクセシブルな名前を追加するため
※設定するラベル名はデジタル庁のデザインシステムより
 https://www.figma.com/community/file/1255349027535859598/design-system-1-4-0
=> アクセシビリティ関連の小さな修正

app/assets/scss/foundation/_normalize.scss
[Chromeに導入予定の新しい CSS 機能](https://developer.chrome.com/blog/css-i18n-features?hl=ja) 対策として
いったん `html` に対して `text-autospace: no-autospace;` を追加しました。
作成時点ではChromeの `chrome://flags/#enable-experimental-web-platform-features` を
Enableにしたときのみ効くCSSだが
ブラウザのデフォルト動作が変わることが想定されているため事前設定。
今後の仕様変更によっては調整必要。
2024年1月現在では`text-spacing-trim` についてはテストができないため未対応。
=> [add] text-autospace: no-autospace;

app/assets/scss/object/components/_breadcrumb.scss
▼関連改善事項
https://www.notion.so/growgroup/iOS17-de501e996864469ab98e2f662dc5cefb
iOS17だと、パンくず内のリンクがクリックできない。
とりあえずaタグをdisplay: inline-flexにする
=> [update] c-breadcrumb : iOS17でパンくずがクリックできない問題の応急処置

app/assets/js/app.js, app/assets/js/fonts.js, app/inc/foundation/_head.pug, webpack.config.babel.js
▼関連改善事項
https://www.notion.so/growgroup/CSS-app-css-42c421162eaf4473a181be1f8764fd97
フォント読み込み用の記述をapp.cssから分離して、
レンダリングブロックを減らす。
https://github.com/growgroup/ach-wp/commit/c2fa79f1b095bbe7bb57e445c3f21313d9fbf3f2
https://github.com/growgroup/ach-wp/commit/390526992325eaa33ff7f6aaace226eaa4244a06
https://github.com/growgroup/ach-wp/commit/3a29dc620cfa31a6c5f890857d73d3cfa211db18
app.jsから フォントの読み込みを除外し（Material Icons以外）
fonts.jsに移動。
※ビルド後は /assets/css/fonts.cssになる
fonts.cssはレンダリングブロックを回避するように変更。
また、app.cssもレンダリングブロックを回避するように変更。
```
//- スタイルシート
block stylesheet
+link("/assets/css/app.css")(rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'")
+link("/assets/css/fonts.css")(rel="stylesheet" media="print" onload="this.media='all'") …
```
=> [add] fonts.js: フォント読み込み用の記述をapp.cssから分離して、レンダリングブロックを減らす

app/archive-twocolumns/category/index.pug, app/archive-twocolumns/category/page/index.pug, app/assets/scss/layout/_offer.scss, app/assets/scss/object/components/_news.scss, app/format/components/_text.pug, app/inc/layout/_global-nav.pug, app/inc/mixins/_misc.pug, app/inc/mixins/_offer.pug, app/index.pug, app/news/category/index.pug, app/news/index.pug, app/result/index.pug, app/twocolumns/index.pug
▼関連改善事項
https://www.notion.so/growgroup/archive-twocolumns-pug-news-HTML-8d7eb6b2646640dca73ff16b2ad89b0a
新人研修や初期の案件の際に分かりづらいと感じるpugの記述の除去・修正
- archive-twocolumns
- /page/のpage-header周辺の記述
- paginationのmixin利用
- .rowを使っている箇所の撤廃
- TOPのnews
- l-offerの中身
- formatの c-table-smのところ
- _global-nav.pugの削除
- format
- 見出しのエリアのコメントが間違っているのを修正
- ol.c-list.is-outlineの内側のolからクラスを消す（ulと統一）
- result
- .u-maxwidth944を.l-container.is-smに変更
- twocolumns
- /page/の2カラム版なので不要な記述を減らす。mixinを利用したものに調整。
=> [update] pug : 旧来の記述が残っているpugファイル群の整理

app/assets/scss/layout/_container.scss, app/assets/scss/layout/_header.scss, app/assets/scss/layout/_main.scss, app/assets/scss/layout/_root-container.scss, app/assets/scss/object/components/_grid.scss, app/inc/foundation/_head.pug, app/index.pug
▼関連改善事項
1.l-main関連
https://www.notion.so/growgroup/l-main-dd7f464e67c5484eb89dc2bd90614f80
2.l-container関連
https://www.notion.so/growgroup/_grid-scss-container-CSS-extend-l-container-f9d68ba7e2114fb2a1b91bd225e46d7f
- l-mainに限らず要素の最大値を基本2560pxにしたい
- c-main-visualをl-mainの中に入れたい
- c-main-visualをl-mainの中に入れる
- bodyの直下に .l-root-container を作成し、max-widthを2560pxとする
- l-mainのmax-width指定は削除
- l-header__contentのmax-widthを2560pxとする（l-headerのright/leftの基準位置は画面端になるため）
position:fixedのright/leftの指定の基準値は画面端になるため
position:fixedで配置する要素についてはmax-width:2560pxが効かない事に留意
- 利用していない .containerを削除し、.l-container単体で機能するように変更
（lp案件等で _grid.scssを削除可能にするため）
=> l-main・l-containerの調整 ＆ l-root-containerの追加

app/assets/js/app/current-nav.js, app/assets/scss/object/components/_menu-list.scss, app/inc/layout/_aside.pug
js-current-navにjs-current-childrenが付いていたら第3階層でもis-currentを付与したいので、current-nav.jsを改良しました。
urlが完全一致しないとis-currentが付与されないので、小階層までチェックし、小階層に滞在してもis-currentを付与したいため。
https://yokogawa-bridge.grgr.blue/company/history/1950/
=> current-nav.jsで下階層にも対応したい

app/assets/js/app/anchor.js
window.onload = function() {
を
document.addEventListener("DOMContentLoaded", function(event) {
に変更。
window.onload = function() {にconsole.logを差し込んでも反応無しでした。
遷移した際にheaderが被さるため。
https://yokogawa-bridge.grgr.blue/company/office/#osaka2
=> ページロード時のanchorがheader分の高さが引けてない

package.json, server.js
▼関連改善事項
https://www.notion.so/growgroup/develop-pug-pug-O-build-pug-js-app-out-dist-w-s-browsersync-pug-ef259e01232946a2838240efaaa7410f
- server.jsでpugを全ビルドしないように設定しているにもかかわらず、
npm scriptsでpugを全ビルドしているためpugの処理が重い？
- npm startをした時点で生成されるページ数の数だけbrowsersyncがブラウザをリロードさせる？のか
リロード挙動がおかしい場合がある
以下の処理を削除
```
"develop:pug": "pug -O build/pug.js app --out dist -w -s",
```
- pugファイルの変更時にbrowsersyncのリロードが走るようにする
- node-notifierが走る必要がない気がするので切る
- npm start中はdist内にhtmlファイルを生成しなくなりました（browsersyncのレスポンスでのみpugをコンパイルします）
- pug変更時のブラウザリロード動作が軽快になりました
- build時の挙動に変更はありません
- mixin等にミスがあるとき、今までは常にターミナルにエラーが出ましたが、
mixinを使用するページを開いているときのみエラーが出るようになりました（たぶん）
=> [update] server.js : npm start 時のpugビルドの挙動を変更

app/assets/js/app/current-nav.js, package-lock.json, package.json
▼関連改善事項
https://www.notion.so/growgroup/current-nav-js-url-68e0f626216746019bf26c4565644086
current-nav.jsで、hrefに記載のurlがhttpではじまる場合にURLのパス部分だけを返すようにする処理について
urlパッケージの利用をやめて、JavaScriptでなんとかするように変更
app.jsの最終ビルドサイズが45KBくらい小さくなる
hrefに記載のURLがhttpやhttpsではじまる場合も、パス部分を正しく抽出しており
期待通りのタイミングでis-currentが付与される
=> [update] current-nav.js : urlの利用をやめる

app/assets/js/app/swiper.js, app/assets/scss/foundation/_mixin.scss, app/assets/scss/layout/_page-header.scss, app/assets/scss/object/components/_card-download.scss, app/assets/scss/object/components/_card-post.scss, app/assets/scss/object/components/_forms-document-detail.scss, app/assets/scss/object/components/_gallery-card.scss, app/assets/scss/object/components/_gallery-logo.scss, app/assets/scss/object/components/_gallery-slider.scss, app/assets/scss/object/components/_main-visual.scss, app/download/index.pug, app/download/page/index.pug, app/format/components/_other.pug, app/inc/layout/_footer.pug, app/inc/layout/_header.pug, app/inc/mixins/_main-visual.pug, app/inc/mixins/_misc.pug, app/inc/mixins/_page-header.pug, app/index.pug
▼関連改善事項
https://www.notion.so/growgroup/bg-img-bgimg-img-picture-d54a33af7afd435c9b98f6b90aea0aee
HTML上にstyle属性でbackground-imageを置く方法（`+bgimg`）をやめる。
- すべての画像（写真とか）にbackground-imageを利用すると若干レンダリングパフォーマンスに悪影響があるため
（プリロードスキャナ等のレンダリングの仕組みの都合上）
- もともとbackground-size:cover を利用するためにbackground-image指定をしていたが、
object-fit:cover で対処できるようになり、background-image指定である必然性も無くなったため。
- WP側でビジュアルエディタ上で画像差し替えするにもimgタグの方が良い場合が多いため。
- picture タグ用のpug mixinの追加
- object-fit用のscss mixinの追加
- 既存のpug/scssから`+bgimg`関連の記述の除去
※引数にcontainを渡す事もできます
```
&__image {
img {
@include img-option();
aspect-ratio: 16/9;
}
}
```
```
c-hoge__image img {
width: 100%;
height: 100%;
max-width: initial;
object-fit: cover;
aspect-ratio: 16/9;
}
```
※loading=lazy属性を付ける場合（ファーストビュー画像以外）では、display:noneでの切り替えも有効です。
``` …
```
=> [add] +picture(pug) / @include img-option()(scss)

app/assets/js/app/accordion.js, app/assets/js/app/utils.js
▼関連改善事項
https://www.notion.so/growgroup/JavaScript-utils-b280955b3c0c4b2d92a07d496861eeaa
- window.matchMediaを簡単にサイトのあちこちで使えるようにするための便利関数追加。
- 追加関数を利用したaccordion.jsの調整
window.matchMedia / mediaQueryList.onChangeはサイト内の随所で使うには書くことが多いため
指定を多少シンプルにする関数を追加しました。
```
import Utils from "./utils";
const utils = new Utils();
utils.responsiveMatch(
() => {
//match時の処理
},
() => {
//unmatch時の処理
},
//メディアクエリ（"max-width: 949px"など。省略可）
);
```
MediaQueryList: change イベント: https://developer.mozilla.org/ja/docs/Web/API/MediaQueryList/change_event
参考: https://deep-space.blue/web/3186
動作サンプル: https://codepen.io/miral_kashiwagi/pen/zYXEgVN
accordion.jsのdata-accordion-responsiveは
ウィンドウリサイズ後再読み込みしたときのみ効果がありましたが、
再読み込み無しで効果が出るようにしました。
▼動作
https://capture.dropbox.com/F4iW1tC2r0kc0YhY
=> [add] Utils.responsiveMatch()

app/assets/scss/foundation/_normalize.scss
▼関連改善事項
https://www.notion.so/growgroup/normalize-scss-min-width-0-c057ed135d2c49de91758de2b596eb66
normalize.scssに対して全称セレクタで `min-width:0` の追加。
display:flex（やgrid）関連で、min-width:0が付いていないと予想と違う動作になることがあるため
▼参考
https://github.com/nicolas-cusan/destyle.css/issues/23
https://zenn.dev/kagan/articles/css-chrome-aspect-ratio
=> [update] normalize.scss : min-width 0 追加

app/inc/_settings.pug, app/inc/mixins/_anchor.pug, app/inc/mixins/_cssrules.pug, app/inc/mixins/_misc.pug
関連プルリク https://github.com/growgroup/gg-styleguide/pull/122
▼関連改善事項
https://www.notion.so/growgroup/aex-a-ex-https-config-rootpath-6bef52e832fe45a2a9275604a6764c85?pvs=25
https://www.notion.so/growgroup/bgimg-scss-ee170bdf87e041399977837bbd3ab18e
https://www.notion.so/growgroup/pug-a-mixin-4-64edcb32b5294f0b88958799e6d1fda2
- +aや+img等の引数に、httpではじまるURLが渡されたときは config.rootpath を付けない
- +aや+aeでhttpではじまるURLや、.pdfで終わるURLが渡されたときは target="_blank"自動付与
※この改善で **+a-exと+aexは不要に**なり、基本的に +a と +ae（+cの中で利用）だけで良くなる
「実際どうなる」の項目を参照。
```
setSrcValue = function (src, path) {//+img()用のsrc属性判定＆設定
if (src === undefined) {
return undefined;
} else if (src.startsWith('http')) {
return src;
} else {
return config.rootpath + path + src;
}
}
setHrefValue = function (href) {//+a()用のhref属性判定＆設定
if (href === undefined) …
```
=> [update] +a, +ae, +img, +picture, +video, +bgimg : 引数がhttpからはじまるかどうかの判定処理追加

app/assets/scss/foundation/_normalize.scss, package-lock.json
▼関連改善事項
https://www.notion.so/growgroup/image-rendering-webkit-optimize-contrast-Safari-CSS-Safari-6468c78484474a4ab96f194e1b75927c
以下のSafariでは効かないでほしかった（Chromeのみで効いてほしい）CSSが、Safariでも効いている
```
@media screen and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: .001dpcm) {
body {
image-rendering: -webkit-optimize-contrast;
}
}
```
CSSハックを別のものに取り替える応急措置
```
_:lang(x)::-internal-media-controls-overlay-cast-button, body {
image-rendering: -webkit-optimize-contrast;
}
```
SafariとFirefoxでは該当のimage-renderingが効かなくなった
=> [update]   image-rendering: -webkit-optimize-contrast CSSハック変更

app/assets/scss/foundation/_mixin.scss, app/assets/scss/object/components/news-lg.scss, app/assets/scss/object/components/news.scss, app/assets/scss/object/utility/text.scss, app/news/index.pug
▼関連改善事項
https://www.notion.so/growgroup/news-CSS-235e3adbc9a042c989f544b74d0d1ac2
WordPress実装時に「お知らせ」系の投稿機能では、
必ず同じclass名に対してリンクのありverと、なしverが存在する
```
<a class="c-news__block" href="#">リンクあり</a>
<div class="c-news__block">リンクなし</div>
```
リンク無しverのときは、hoverの反応をあらかじめ切っておきたい。
- .c-news__blockにあらかじめ `:any-link:hover` を設定しておく
- @mixin hover に :any-linkを仕込んでおく（ついでにmixin group-hoverも作っておく）
- .u-hover-disabled を作っておく
```
&__block{
&:any-link:hover {
background-color: $color-secondary;
}
}
```
▼妥当な指定方法の研究
https://codepen.io/miral_kashiwagi/pen/zYQQoxr
上記より、aタグのみにhoverを設定するより、:any-link:hoverとする方が
- 動作的に妥当
- 日常的に書くのが楽
※ただしmedia queryのソートの都合で期待値とCSSの効き方が違うので、いったん標準とはしていない
```
@mixin hover {
@media (hover: hover) {
&:where(:any-link, :enabled, summary):hover {
@content;
}
}
}
@mixin group-hover { …
```
=> :any-link:hover の追加（主にお知らせ一覧）と @mixin hoverの調整、@mixin group-hoverの追加

app/archive-twocolumns/category/page/index.pug, app/news/category/page/index.pug
以下のように変更。
- tableにtheadを追加
- HTML　要素タグテストを除去
- divがふたつ隣接したときにmarginがあることを確認
=> [update] news & archive-twocolumns : ベースのHTMLをWPに近づける

app/inc/layout/_footer.pug, app/inc/layout/_header.pug
▼関連改善事項
https://www.notion.so/growgroup/layout-222ab7221f5f45b89e0594fbbea68442
以下のように`current.id === "contact"` を `||` でつないでいくのはページ数が多いときに大変なので
```
if (current.id === "contact" || current.id === "confirm" || current.id === "complete") {
className = "l-header is-simple"
}
```
以下のように配列に追加するだけでよくしたい
```
var currentList = ["main-store","contact-wood","contact-machine","contact-forest","entry" , "confirm" ,"complete"]
```
isSimplePages配列に追加すると、 is-simpleが追加されるようになりました。
```
-
var className = "l-header"
var isSimplePages = ["contact", "confirm", "complete"]
if (isSimplePages.includes(current.id)) {
//isSimplePagesにcurrent.idが含まれている場合
className += " is-simple"
} else {
//それ以外のとき
className += " js-fixedheader"
}
if (current.id === "home") {
className += " is-home"
}
```
=> [update] l-header, l-footer

app/assets/js/app/anchor.js, app/assets/scss/foundation/_normalize.scss, app/assets/scss/foundation/_settings.scss, app/assets/scss/layout/header.scss, app/assets/scss/layout/section.scss, app/format/components/_tab.pug, app/format/index.pug, app/index.pug
▼関連改善事項
https://www.notion.so/growgroup/anchor-margin-top-6b60dd228e124fa0bcda3dd4debef252
▼デモ
npm start 後、 localhost:3000/format/
marginが付いている要素の時に、paddingが付いている要素と見かけ上同じ位置にアンカーが来るようにしたい場合がある
別ページから /hoge/#hoge へリンクしたときの動作を改善したい。
最近の案件だと、ページを開く→ロードが終わってからスクロール位置を計算し直すのでガタつく
scroll-padding-top と scroll-margin-topによる計算方法の導入。
参考 https://note.com/eightbe/n/n9eac9c7b3cb0
PCとSPの基本のヘッダー高さを設定
```
// ==============================
// # 5. Layout
// ==============================
// ヘッダーの高さ
$header-height: 100 !default; // スクロール位置をずらす計算にも使います
$header-height-sp: 55 !default; // スクロール位置をずらす計算にも使います
```
上記scss変数は最終的にhtml要素のscroll-padding-topに入る。
```
html {
<略>
scroll-padding-top: var(--header-height); //スクロール位置の調整が不要な場合は 0 にする
}
```
```
.c-hoge{
scroll-margin-top: rem-calc(100); //$header-height + …
```
=> anchor.jsのズラし量計算を、scroll-padding-topとscroll-margin-topに依存させる

package-lock.json, package.json, server.js, webpack.config.babel.js, webpack.style.config.babel.js
参考： https://webpack.js.org/guides/build-performance/#compile-in-memory
- npm start 時のCSSの変更反映を速くしたい
元←　→本プルリク
https://github.com/growgroup/gg-styleguide/assets/97862690/99d940e7-66e0-477f-9f9d-1f34e0be020b
npm start 時に、style.cssの実態ファイルを生成せず、メモリにだけ持つようにした。
※いままでのファイルを書き込んで
　書き込まれたファイルをbrowsersyncで検出してからリロードする
　形式だとリロードまでにロスがあるため 
もしWP工程でローカルでスタイル調整作業するときにnpm startによるwatchを活用していた場合、
npm start中のCSSの変更は（別途buildするまで）localhost:8000側には反映されません
（実体ファイルに書き込まないので）
=> server.js : npm start時にwebpack.style.config.babel.jsの処理をdistに書き込まないようにする 

app/assets/scss/object/utility/_index.scss, app/assets/scss/object/utility/a11y.scss, app/inc/mixins/_searchform.pug
▼関連改善事項
https://www.notion.so/growgroup/WAI-ARIA-1-2-span-aria-label-visually-hidden-08cc365b58c94fea8ebeba00a16c8848
WAI-ARIA1.2からspanにaria-labelを付けるのがNGになったので、visually-hiddenに変更。
（WAI-ARIA 1.1まではつけてもよかった）
デジタル庁 https://www.digital.go.jp/ のCSSにある
.u-visually-hidden
=> [update] searchform.pug : spanのaria-labelをvisually-hiddenに変更

app/assets/scss/foundation/_normalize.scss, app/assets/scss/object/components/toc.scss
▼関連改善事項
https://www.notion.so/growgroup/toc_container-width-100-important-45a98cd720a24760aafff4f04e789aaa
https://www.notion.so/growgroup/normalize-body-291513458dde431bbd1cb024e5c48285
- https://github.com/growgroup/gg-styleguide/pull/144 で
作成した変数がbodyの上方向marginに適用されていなかった問題の解決
- https://github.com/growgroup/gg-styleguide/pull/136/ で
削除した!importantのうち、WPプラグイン都合で必要なものがあったので復活
=> 過去の修正にまつわる小さなCSS調整

app/assets/scss/foundation/_mixin-post-content.scss, app/assets/scss/foundation/_normalize.scss
▼改善事項
https://www.notion.so/growgroup/CSS-dd31f6f1f989431784853c4b6eeeb40a
https://ics.media/entry/240411/ のおすすめ設定を反映し、
l-post-contentにある `word-break: break-all;` を削除
- word-break: break-all;では英語の場合に単語の途中で改行されてしまい、文章の意味が分からなくなる
- word-break無しだとURLが改行せず、コンテンツをぶち抜いてしまう問題がある
▼サンプル（このテキストはGit内には反映していません）
- URLは自動改行する
- 英単語内での改行は起きない
=> [update] normalize : 改行系

app/assets/scss/object/components/forms.scss, app/contact/index.pug
▼改善事項
https://www.notion.so/growgroup/HTMLtoCF7-Converter-gg-styleguide-e9a6289f408749c29698bbf2a7ab0035
- /contact/の標準をContact Form 7 用のHTML/CSSに変更（主にradio / checkbox）
- HTML to CF7 Converter用に調整する
- radio / checkboxのHTML構造が変わりました
- name値を英語で入れるように変更になりました
- メールアドレスと電話番号は input typeをemailやtelで設定するように変更になりました
=> [update] /contact/ 標準を Contact Form 7 仕様に

app/assets/scss/object/components/slidebar-button.scss, app/inc/mixins/_slidebar.pug
▼改善事項
https://www.notion.so/growgroup/c-slidebar-button-HTMLCSS-1bfed8b7a3ab48a18df1a45f9520cbdc
- ×の中心位置が、ズレがちな問題の解決
- 改修時にハンバーガーメニューボタンを出すタイミングの変更がしづらい問題の解決
- （ついでに）ボタン内にテキストがないとき、ラベルのないボタンになる問題を軽減
線の配置の方法を根本的に変えることで、以下のような現象を防ぐようにしました。
▼現象
▼参考
https://shibajuku.net/make-hamburger-button/
WP改修案件で、ハンバーガーメニューボタンを出すタイミングを1200pxからに変えたいな〜とおもっても
そもそもボタンのスタイルが950px以下からしか当たっていないので、めちゃくちゃ苦労する問題を改善しました
（ボタンのスタイルはメディアクエリで囲まずに書き、display:noneの設定をlarge upでするようにした）
▼該当変更箇所
https://github.com/growgroup/gg-styleguide/pull/151/files#diff-d60a8951cf2d5a04b98cd273debf78d188f5c2da3df1f26f53c8069f992ecf19L12-L14
ハンバーガーメニューボタンのスタイルとして、線しかない場合に、
aria-labelを書かない限り、ラベルのないボタンになる問題を解決するため visually-hiddenでテキストを追加しました。
また、CSS変更のついでに、この部分の[空のパルパブルコンテンツ](https://dskd.jp/archives/112.html)問題も解消しました。
▼該当変更箇所 …
=> [update] c-slidebar-button : ×のときの交差点が中心を捉えやすいように変更

app/assets/js/app.js, app/assets/js/app/swiper.js, app/assets/js/app/utils.js, app/assets/scss/object/components/card.scss, app/assets/scss/object/components/gallery-logo.scss, app/download/page/index.pug, app/format/components/_other.pug, app/inc/mixins/_main-visual.pug, app/index.pug
▼改善事項
https://www.notion.so/growgroup/gg-styleguide-swiper-5b61aae658b3490e908cde35a2661a28
https://capture.dropbox.com/QUrg0wshbYTDVpos
※会社紹介ギャラリー として設置してあったサンプルは、
　カードスライダー（スマホとPCで発火最小枚数をが異なる）のサンプルに置き換わりました。
- メソッドを分けてコードの見通しをよくする
- jQuery非依存の書き方でいったん統一（追加するときはjQueryでも可）
- imagesLoadedのimport処理を heightline.jsに依存しないようにする
- コーディング規約に基づき、js発火用classとスタイリング用classを分ける（jsでCSSセレクタを使う場合 `js-` にする）
※サンプルの各HTML（pug）は TOP、 /format/ 、/download/page/ 上にあります。
https://github.com/growgroup/gg-styleguide/blob/eec6932a150c5f5f74d4cfe47e8b45f6a1611714/app/assets/js/app/swiper.js#L98-L102
※そもそもロゴループスライダーの動作が不安定なのだがそれはいったん考えないものとする
https://github.com/growgroup/gg-styleguide/blob/9a270ab1b171ff333ac136e4686b77e5117c9769/app/assets/js/app/swiper.js#L152-L166 …
=> [update] swiper :コード整理

app/assets/scss/foundation/_mixin.scss, webpack.style.config.babel.js
▼関連改善事項
https://www.notion.so/growgroup/CSS-105eef14914a80a28fe6ffeeb3fb435d
参考：「幅変更でスタイル消失!?「メディアクエリ設定」の落とし穴」 https://liginc.co.jp/421566
ブラウザまたは表示スケール（windows）が100%以外の値になっているとき、
小数を持つ表示領域幅が発生する可能性がある。
.l-headerのナビを消し.c-slidebar-button を表示させるときのように
min-width(750px)とmax-width(749px)を使うと、749.5pxのときはどちらのCSSも当たっていない状態になるため
※メディアクエリは実際にはem値
- downのときは max-widthを従来通り使う
- upのときは min-widthではなく notでdownのときのメディアクエリを否定する
- onlyのときはメディアクエリの入れ子を使う
- Range SyntaxはiOS16.4から対応であり2024年9月時点だとまだ利用に慎重になる必要があるため
もっともよく使う以下のスタイルの上書きで確認
```
.c-hoge {
color: green;
@include breakpoint(medium down){
color:blue;
}
@include breakpoint(small only){
color:red;
}
```
```
.c-hoge {
color: green;
}
@media screen and (max-width: 59.3125em) {
.c-hoge {
color: blue;
}
}
@media screen and (max-width: 46.8125em) {
.c-hoge { …
```
=> breakpoint() で生成するメディアクエリを漏れ無しダブり無しになるよう修正

app/assets/scss/foundation/_mixin-post-content.scss, app/format/components/_text.pug
▼改善事項
https://www.notion.so/growgroup/l-post-content-table-thead-CSS-be914716374b4324ba8e777fccc60481
---
- tbodyのth,tdのみにスタイルを付ける設定になっていたものについて、tbodyのみの縛りを外す
- WordPressのコアブロックのスタイルの影響を考慮したデフォルトのスタイル設定を追加
=> c-tableのスタイルをtbodyのみ→theadのth, tdにもスタイルが当たるように変更

app/assets/scss/editor.scss
`.l-post-content > * + *`のスタイルが
そのまま`#growp-editor-wrapper.post-type-post  > * + *` で出力されると
意図通りにはCSS適用されない問題の対応
=> editor.scssの &.post-type-post を &.post-type-post .is-root-container に

app/assets/scss/foundation/_form-controls.scss, app/assets/scss/foundation/_mixin-post-content.scss, app/assets/scss/object/components/buttons.scss, app/assets/scss/object/components/tabs.scss, package-lock.json, package.json, webpack.config.babel.js
▼改善事項
https://www.notion.so/growgroup/node-sass-deprecated-warning-10eeef14914a8075ad60ff5c7222d51c
https://github.com/growgroup/gg-styleguide/pull/159 でsassのバージョンを上げたため
いくつかの Depracated がでているので、できるだけ出ないようにしました。
```
LOG from ../node_modules/sass-loader/dist/cjs.js sass-loader ../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!../node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!../node_modules/sass-loader/dist/cjs.js!./assets/scss/style.scss
<w> Deprecation The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
<w> 
<w> More info: https://sass-lang.com/d/legacy-js-api
<w> 
<w> null
<w> Deprecation Sass's behavior for declarations that appear after nested
<w> rules will be changing to match the behavior specified by CSS in an upcoming
<w> …
```
=> #159 以降ででるSass系のDepracated のWarningが出ないように微調整する

app/assets/js/app/slidebar.js, app/assets/scss/object/components/slidebar-menu.scss
▼改善事項
https://www.notion.so/growgroup/slidebar-js-ResizeObserver-defaultOptions-10ceef14914a807896fad7cf84bc8eb3
https://www.notion.so/growgroup/slidebar-js-ce0fba7f2d3348039c1c0ee227ea4e31
https://www.notion.so/growgroup/js-c-block-document__slider-js-b754a08f9b154c138948e464a0abb24c
slidebar.jsおよび slidebar-menu.scssの以下の変更
- https://github.com/growgroup/gg-styleguide/pull/111 の、画面サイズの指定について数値を defaultOptionsに設定することで、外部JavaScriptから数値を書き換え可能にする（WP改修用）
- ページ内リンク時の挙動のコメントアウトを外し、セレクタを `c-slidebar-menu` から `this.options.menuSelector` を参照するように変更
- ついでに https://github.com/growgroup/gg-styleguide/pull/151 でslidebar-button はメインのスタイルをメディアクエリの外に出したのに、-menuの方は行っていなかったので実施
=> slidebar.js内の画面幅指定箇所をdefaultOptions＆ページ内リンク用の記述のコメントアウトを外す＆slidebar-menu.scssの調整

app/assets/js/app/gsap.js, app/assets/js/app/utils.js
▼改善事項
https://www.notion.so/growgroup/Figma-GSAP-03ae19a5f2114c3c9e7290855a562b96
Figmaで設定するイージングのうちStiffness,Damping,Massで指定する方のスプリングを、GSAPで再現できるようにする関数の追加
https://github.com/growgroup/gg-styleguide/pull/165/files#diff-e0cbe79841a5563f5ee79788cdd4c6238f55d3fe940017a86799416f74329eec
複雑なアニメーションを要するサイトのとき、run() に全部書くより
処理ごとにメソッドを分けた方が良さそうだったのでそのような構造に整理。
また、インスタンス化後に呼び出す方はほとんど使わない気がするのでいったん削除。
=> gsap.jsの調整＋Figmaのスプリングに対応するための関数の追加

.vscode/extensions.json
【フロントエンド課】
VScodeの推奨拡張機能をプロジェクトメンバーで統一するため
.vscode/extensions.jsonを作成（phpstorm利用者には影響なし）
対象の拡張機能は以下
- Japanese Language Pack for Visual Studio Code（日本語化）
- EditorConfig for VS Code（コードを一貫したスタイルで編集）
- Indent Rainbow（インデントを見やすくするやつ）
=> [add]extensions.json

app/assets/scss/foundation/_mixin-post-content.scss
▼改善事項
https://www.notion.so/growgroup/gg-styleguide-c-list-material-icon-01d55fdeb04445f79d837df00583f59d
.c-list.is-iconのデフォルトのアイコンを、material iconsの○ではなく
以下のような感じで作るやつに変更。
```
width: rem-calc(4);
height: rem-calc(4);
border-radius: 50%;
background: $font-base-color;
```
ただの●なら `--_icon-size: #{rem-calc(4)};` を変更するとサイズ変更可能。
必要に応じて全体的に書き換えてOK
```
&::before {
--_icon-size: #{rem-calc(4)};
content: "";
width: var(--_icon-size);
height: var(--_icon-size);
background: $color-primary;
border-radius: 50%;
top: calc(1em * #{$font-base-line-height} / 2 - var(--_icon-size) / 2);
left: 0.25em;
position: absolute;
}
```
=> [update] c-list.is-icon

app/archive-twocolumns/category/index.pug, app/archive-twocolumns/category/page/index.pug, app/archive-twocolumns/index.pug, app/blocks/index.pug, app/contact/complete/index.pug, app/contact/confirm/index.pug, app/contact/index.pug, app/download/index.pug, app/download/page/index.pug, app/format/index.pug, app/inc/_settings.pug, app/inc/foundation/_head.pug, app/index.pug, app/news/category/index.pug, app/news/category/page/index.pug, app/news/index.pug, app/page/index.pug, app/result/index.pug, app/sitemap/index.pug, app/twocolumns/index.pug
▼改善事項
https://www.notion.so/growgroup/description-description-114eef14914a800693b7c122e9a40a12
基本的にページのdescriptionについて、ページごと完全に個別のものを入れることがないので
ページタイトル+サイト全体のdescription＝ページのdescriptionをデフォルト値にして、
ページのpug側で上書きできる構造に変える
1. app/inc/_settings.pug にTOPページ用の説明文を入れる
2. app/inc/foundation/_head.pugの `desc = config.site.title+'の'+current.title + 'のページです。' + config.site.description` を必要に応じて調整
3. ページごとに全く異なる説明文を入れるときは、各ページのpugから設定
=> [update] _head.pug : サイトの説明文のデフォルト設定と上書き設定

app/download/page/index.pug
▼改善事項
https://www.notion.so/growgroup/download-page-format-micromodal-121eef14914a807587e6da72a15adcff
https://github.com/growgroup/gg-styleguide/pull/156 のときの変更が、
/download/page/で漏れていたため、その反映。
`+ae("/assets/images/img-card-01.jpg").image.js-modal-image`
↓↓
`+ae("/assets/images/img-card-01.jpg").image.c-modal-link.js-modal(data-modal-type="image")`
=> [update] download/page/ : モーダル発火用のJS変更が反映できていなかったのを修正

.gitignore
▼改善事項
https://www.notion.so/growgroup/gitignore-base-ignore-131eef14914a8059a60bef5dcf6f9d6a
.gitignore から base/ を削除
=> [update] .gitignore : base/ の削除

app/archive-twocolumns/category/index.pug, app/archive-twocolumns/category/page/index.pug, app/format/index.pug, app/inc/mixins/_breadcrumb.pug, app/news/category/index.pug, app/news/category/page/index.pug
▼改善事項
https://www.notion.so/growgroup/Mixin-2a02c566afab46bbb526bcbc396a89fe#150e1e20a3d041fbab6ac2ea26fa678f
- c_breadcrumbのmixinを再帰的なmixinに変更
- class名などの属性を `&attributes(attributes)` で付けられるようにする
1. 階層が深いページのときのパンくずの書き方が変わりました。
2. 階層が大変深いサイトのときc_breadcrumbのmixinを修正する必要が無くなりました。
```
+c_breadcrumb("お知らせ","news","カテゴリ","category")
```
```
+c_breadcrumb({
paths: [
{url: "news", text: "お知らせ"},
{url: "category", text: "カテゴリ"},
]
})
```
=> [update] c_breadcrumb : 再帰的なmixinに変更して階層が深いサイトに対応する

app/assets/js/app/anchor.js
以下の２つのリンク機能があった時に共存させる
A：ページAではページ内アンカーとして利用
B：ページA以外ではページAの指定場所への直接リンクとして利用
例
```
+a("/pageA/#block01").js-anchor block01
+a("/pageA/#block02").js-anchor block02
+a("/pageA/#block03").js-anchor block03
```
実装コードは以下changed fileを参照
=> [update]anchorJSで別ページリンクと共存させる

app/assets/scss/object/components/forms.scss, app/contact/index.pug
▼改善事項
https://www.notion.so/growgroup/input-growp-name-11beef14914a800092c8d6cf6a0186df
https://www.notion.so/growgroup/1-2input-123eef14914a80b8ae36d31585e835e9
1. /contact/ の name値デフォルトをWPに近づける
2. 行に2つのinputを入れる場合にalign-items を flex-startにする実装方法の作成
name値を`your_name` などアンダースコアにしていたが、
WPのデフォルトが `your-name` だったのでハイフンに統一
元々のCSSでは`&__flexbox` `&__flex-al` に`align-items:center` が指定されているため、
エラー発生時に以下のようにラベルがinputよりも下に落ちる問題がある
上記を避けるために `align-items:baseline` が利用できるが、
webkitのバグで [inputのplaceholderが消えたときにbaselineの計算対象が変わるらしく](https://teratail.com/questions/gdochtn5mao08h)、入力した瞬間にラベルが移動する問題が発生した。
`&__flexbox` `&__flex-al` に`align-items:flex-start` を利用した上で、適切なサイズの `margin-top` または`padding-top` を指定する方法をデフォルト実装に変更した。
=> /contact/ の name値デフォルトをWPに近づける & 1行に2つのinputを入れる場合にalign-items を flex-startにする実装方法の作成

app/assets/scss/foundation/_mixin.scss, app/assets/scss/object/components/breadcrumb.scss, app/assets/scss/object/components/icon-font.scss
▼改善事項
https://www.notion.so/growgroup/mixin-icon-font-flex-shrink-0-137eef14914a8045945bf4d939fb8d2f
- `mixin icon-font()` に `flex-shrink: 0;` の追加。
- .c-icon-font にincludeするCSSが `mixin icon-font-size-control()` のものを含むように変更
- 上記に伴いc-breadcrumbが崩れるので崩れないように調整
```
.c-icon-font {
font-family: "Material Icons";
font-weight: normal;
font-style: normal;
line-height: 1;
letter-spacing: 0;
text-transform: none;
overflow: hidden;
display: inline-block;
flex-shrink: 0;
width: 1em;
height: 1em;
}
```
- display:flex でアイコンと文字を横に並べたとき、アイコンの表示が消えたり意図しないものに変化するのを防ぎます
- `.c-icon-font` で設置したアイコンについて、ロード時に文字が見えて横に伸びるのを防ぐと共に、上記の効果を付与します。
=> [update] mixin icon-font

app/assets/scss/foundation/_settings.scss, app/assets/scss/object/components/slidebar-menu.scss
slidebar-menu.scss内にて、&__linkにbackgroundが設定されていため、$slidebar-menu-bg変数の値を変更しても、一発でslidebarの背景色が変わらなかった。
文字色の設定、ボーダー色の設定も、_settings.scss内の変数で一括指定できるように変更。
- _settings.scssに新規で$slidebar-menu-text-color変数を設定
- slidebar-menu.scss内
- &__listのbackground削除
- &__parentのcolor, border-bottomのカラー設定を変数に置き換え
=> [update]slidebar-menuの背景色とテキストカラーの変数設定、scss記述整理

app/assets/js/app/slidebar.js, app/inc/mixins/_slidebar.pug
▼改善事項
https://www.notion.so/growgroup/slidebar-inert-inert-true-inert-inert-153eef14914a800f963cfdb8d0622634
---
https://github.com/growgroup/gg-styleguide/pull/101 で追加したinert属性について、
bool属性（`<div inert>`のように値が不要な属性）で値を使う場合は `属性名="属性名"` の方が正確だったので
以下のように修正。
```
+c.slidebar-menu.js-slidebar-menu.is-top-to-bottom(inert="inert")
```
その上で、JSの処理も同様に修正。
=> slidebar : inert属性値の使い方の修正

app/assets/js/app/swiper.js
▼改善事項
https://www.notion.so/growgroup/Swiper-threshold-145eef14914a80efa7a0ed3866c98306
---
マウス（タッチ操作）でのスワイプでスライド切り替えができる仕様の時、
スライド内のリンクをクリックできない場合がある
参考情報：https://ruka-tech.xyz/useful-info/make-swiper-more-user-friendly
swiper.js内の各サンプル実装コードに、 `threshold:10,` を追加
```
// loopedSlidesLimit:false, //スライドの複製を無制限にする
// loopedSlides: 2, //スライドの複製数を指定する
```
こういうデザインのスライドショーで、スライド数が1〜2枚のとき（※1枚のときはスライド発火を切らないパターンのとき）
`loopedSlides` を書いてもスライド切り替え時に「一瞬スライド枚数が足りない」問題が起きがち。
そのとき `loopedSlidesLimit:false`にすると上手くいくのでそのヒントとしてコメントを追加。
=> swiper : thresholdのパラメーターをデフォルトに追加（スワイプする要素内のリンクがクリックできない場合がある問題の解決）

app/assets/scss/layout/section.scss, app/assets/scss/object/utility/margin.scss
.l-section、u-mbsの繰り返し処理の簡易化
例
旧記述方法
```
.l-section {
&.is-xlg {
padding-top: rem-calc($xlg);
padding-bottom: rem-calc($xlg);
@include breakpoint(small only) {
padding-top: rem-calc($xlg) * 0.5;
padding-bottom: rem-calc($xlg) * 0.5;
}
}
&.is-lg {
padding-top: rem-calc($lg);
padding-bottom: rem-calc($lg);
@include breakpoint(small only) {
padding-top: rem-calc($lg) * 0.5;
padding-bottom: rem-calc($lg) * 0.5;
}
}
}
```
新記述方法
```
$sizes: (
xlg: (120, 60),
lg: (100, 50),
md: (80, ),
sm: (64, 28),
xs: (32, 20),
);
.l-section {
@each $key, $value in $sizes {
&.is-#{$key} {
margin-top: rem-calc($value);
margin-bottom: rem-calc($value);
@include breakpoint(small down) {
margin-top: rem-calc($value) * 0.5;
margin-bottom: rem-calc($value) * 0.5;
}
}
}
}
```
=> [update]scss繰り返し処理の簡易化

.markuplintrc, package-lock.json, package.json
https://github.com/growgroup/gg-styleguide/pull/159 でmarkuplintのバージョンを4へ上げたものを、2に戻す処理。
permitted-contentsのルールが漏れていたが、追加するとmarkuplintが途中で止まってしまい即時解決が難しいため。
4に上げたときに追加された以下などのチェック項目が削除されることに注意。
- 見出しレベルが飛んでいると警告が出る
- timeタグでdatetime属性を忘れているとエラーが出る
- l-main内の画像に直接classを適用していると警告が出る
=> [update] rollback markuplint 4 to 2

app/assets/scss/object/components/toc.scss
▼改善事項
https://www.notion.so/growgroup/166eef14914a803dbf4df8574c883581
- 目次を閉じる操作をしたとき（WP組み込み後）に、下側余白が広すぎる問題の解決
- （ついでに）リストの左側余白が l-post-content のCSSの影響で余分についていた問題の解決
以下を追加しました。
```
#toc_container.contracted .toc_title {
margin-bottom: 0;
}
```
=> 目次（toc）の見た目の調整

app/assets/scss/editor.scss
改善事項
https://www.notion.so/growgroup/editor-scss-is-root-container-mce-content-body-is-post-type-post-growp-post-content-174eef14914a805bb3ddcd33295973ae
`&:is(.post-type-post) .is-root-container` の部分を
`&:is(.post-type-post,.growp-post-content) :is(.is-root-container,.mce-content-body)` に変更しました。
```
#growp-editor-wrapper {
font-family: $font-base-family !important;
&:is(.post-type-post,.growp-post-content) :is(.is-root-container,.mce-content-body) //投稿画面
{
//max-width: rem-calc(736);
@include l-post-content;
}
```
```
#growp-editor-wrapper:is(.post-type-post,.growp-post-content) :is(.is-root-container,.mce-content-body){display:flow-root}
#growp-editor-wrapper:is(.post-type-post,.growp-post-content) :is(.is-root-container,.mce-content-body)>*+*{margin-top:1em}
など
```
=> [update] editor.scss

app/inc/foundation/_head.pug
▼改善事項
https://www.notion.so/growgroup/favicon-165eef14914a80baa4c7ce0b23c9601c
` +link("/assets/images/favicon.ico")(rel='shortcut icon')` を削除しました。
https://developer.mozilla.org/ja/docs/Web/HTML/Attributes/rel#values:~:text=shortcut
> shortcut リンク種別が icon の前に見られることが良くありますが、このリンク種別は適合するものではなく、無視されるので使用しないでください。
=> remove rel='shortcut icon'

app/assets/scss/foundation/_mixin.scss, app/assets/scss/layout/footer.scss, app/assets/scss/layout/header.scss, app/assets/scss/layout/searchform.scss, app/assets/scss/object/components/banners.scss, app/assets/scss/object/components/block-modal-form.scss, app/assets/scss/object/components/card-download.scss, app/assets/scss/object/components/embed.scss, app/assets/scss/object/components/forms-document-detail.scss, app/assets/scss/object/components/gallery-card.scss, app/assets/scss/object/components/gallery-slider.scss, app/assets/scss/object/components/hero-block-line.scss, app/assets/scss/object/components/menu-list.scss, app/assets/scss/object/components/mm.scss, app/assets/scss/object/components/modaal.scss, app/assets/scss/object/components/modal-link.scss, app/assets/scss/object/components/news-lg.scss, app/assets/scss/object/components/news.scss, app/assets/scss/object/components/pagetop.scss, app/assets/scss/object/components/pagination.scss, app/assets/scss/object/components/searchform-bar.scss, app/assets/scss/object/components/slidebar-button.scss, app/assets/scss/object/components/slidebar-menu.scss, app/assets/scss/object/components/tabs.scss, app/assets/scss/object/components/toc.scss, app/assets/scss/object/utility/text.scss
ほぼすべての&:hoverを @include hover()に置き換え
実案件中で `a:hover{opacity:0.5}`と`@include hover()` を併用したときに、
タッチデバイスで意図せず透けて問題となる事例があったため（タブUIのような、ページ遷移を伴わないaタグにて）
- タッチデバイスで `a:hover{opacity:0.5}` のスタイルが効かなくなる
- そのほかは、普段 `@include hover()` でホバースタイルを書いていれば大きな変化はなし
- gg-styleguide上に初めから存在するスタイルに関して、CSSの記述順序が変化した都合上スタイルの当たり方が変わっているものがある可能性があります
（`@media` で囲まれたものが、出力されるCSSの最後にまとまるため、適用されるCSSが変わることがあるかも）
l-headerのサブナビ展開用 `:hover` はタッチデバイスでも展開させたい場合があるので、
`:hover`のままとした
=> [update] :hover to @include hover()

app/assets/scss/foundation/_mixin.scss, app/assets/scss/layout/header.scss
https://www.notion.so/growgroup/min-clamp-mixin-1a0eef14914a80a09fb4f437442600e9
デザインデータ上の数値から、`min()` や `clamp()` の値を容易に作り出すためのmixin
1. vw-calc関数
2. cqw-calc関数
3. min-vw関数
4. clamp-vw関数
```
font-size: min-vw(14);
↓↓
font-size: min(0.875rem, 1vw);
font-size: min-vw(14, 1140)
↓↓
font-size: min(0.875rem, 1.2280701754vw);
```
```
font-size: clamp-vw(16);
↓↓ 画面幅2560pxまでは大きくなり続ける。最小フォントサイズ10px。
font-size: clamp(0.625rem, 1.2280701754vw, 1.9649122807rem);
```
clamp-vw(24, 12); //最小サイズを変えたいとき
clamp-vw(24, 12, 1400);     //画面幅1400pxで大きくなるのをやめたいとき
clamp-vw(24, 12, 1400, 1000); // 計算の基準にするデザインの幅を変えたいとき
container-typeを指定したコンテナのサイズを第2引数として渡して使うと
コンテナのサイズに合わせて要素を可変させられる。
```
font-size: cqw-calc(14,1140); 
↓↓
font-size: 1.2280701754cqw;
```
=> [add] scss functions : vw-calc, cqw-calc, min-vw, clamp-vw

app/assets/scss/foundation/_normalize.scss
https://www.notion.so/growgroup/before-after-box-sizing-border-box-1a5eef14914a80bb896ef85b143ef1c1
`::before` `::after` の疑似要素に`box-sizing:border-box` が効いていない問題の解決として
https://github.com/nicolas-cusan/destyle.css/blob/master/destyle.css を参考に、全称セレクタに当てているCSSを ::before, ::after にも当てるようにしました
=> [update] box-sizing for * selector

app/assets/scss/foundation/_normalize.scss, app/assets/scss/object/components/forms-normal.scss, app/assets/scss/object/components/forms-simple.scss, app/assets/scss/object/components/forms.scss, app/assets/scss/object/utility/text.scss
https://www.notion.so/growgroup/Figma-Chrome-text-decoration-underline-1a5eef14914a80969be4e75dd9cfbbf1
`text-decoration: underline` のスタイルが、
Google ChromeでFigmaのデザインよりも「太い」「文字に近い」問題の軽減
※ただしunderlineを指定するとき `text-decorationo-line: underline` としないと
`text-decoration-thickness: from-font;` が継承されません。
参考: https://deep-space.blue/web/3543
=> [add] text-decoration & underline settings

.stylelintrc.js, app/assets/scss/foundation/_mixin.scss, app/assets/scss/layout/header.scss, config/stylelint-line-height-unit-change.js, package-lock.json, package.json, server.js, webpack.config.babel.js, webpack.style.config.babel.js
https://www.notion.so/growgroup/Figma-line-height-180-line-height-1-8-1a5eef14914a807493fddd84a98d6980
- `line-height: 100%` と書いて保存すると、自動的に `line-height: 1` になるようにする
- ついでに、npm start 中のログの表示を整理・一部SCSSの記述を調整
stylelintを `npm start` 中に自動実行するようにしました。auto fix機能で自動でline-heightが書き換わります。
（PhpStormでは、一度ファイルからフォーカスを外さないと見かけ上は更新されません）
参考：https://qiita.com/pons_cawaii/items/476d1953aa7b34664471
▼動作
https://github.com/user-attachments/assets/83d02d6e-dcb4-42a0-86cf-bfd26c5e0596
ログ表示を調整して、stylelintの実行結果を見やすくしました
=> [add] stylelint-line-height-unit-change

app/assets/js/app.js, app/assets/js/app/dropdown-text-sync.js, app/assets/js/app/dropdown.js, app/assets/scss/layout/header.scss, app/assets/scss/object/components/_index.scss, app/assets/scss/object/components/lang-selector.scss, app/inc/layout/_header.pug
https://www.notion.so/growgroup/js-896e9a802c0a4e6fa9b211997c2cecb2
https://www.notion.so/growgroup/17beef14914a80ceb4b9d2f7e50320ab
https://www.notion.so/growgroup/header_megamenu-e7fd25061ed94e34af8c0df7c3c3f596
- l-header__submenu の展開をCSSから、JavaScript制御へ変更
- select風言語切り替えナビゲーションのサンプル実装追加
https://github.com/user-attachments/assets/626f123f-e7aa-44aa-bdb9-094f8106604e
- dropdown.js を追加
- header.pugとheader.scssの書き換え
- サイズの大きなメガメニューをもつ場合に、ページを開いた瞬間からメニューが展開していると、現在のページが分かりづらい問題を解決しました
- liからマウスが離れたとき直ちにメニューが閉じるため、斜め方向にマウスを移動したときにメニューが閉じやすい問題を軽減しました
- 上記の問題をCSSで軽減したとき、消え終わったように見えるメニューの位置にマウスを移動すると、再度展開する問題を軽減しました
data属性で振る舞いをコントロールできます。
必要に応じて dropdown.js を編集し、アニメーションの種類を追加したり、アニメーションの詳細を変更したりしてください。
```
// hoverで展開・fadeIn
.c-dropdown.js-dropdown …
```
=> [add] dropdown.js & dropdown-text-sync.js

app/assets/scss/foundation/_mixin.scss
コンテナクエリ `@container` をmixinで使えるようにしておく
https://www.notion.so/growgroup/container-mixin-191eef14914a80609513f654efb19f08
1.  対象の親にcontainer-typeを付与する
2.  スタイルを当てたい要素に `@include container()`をつける
- 800px以上の時に反映したい（以上）
- `@include container(800 up)` 
- 300px以下の時に反映したい（以下）
- `@include container(300 down) `
- 100〜250pxの間の時に反映したい（範囲） 
- `@include container(100 250) `
- `@include container(250 100)` でもOK
=> [add]mixin_コンテナクエリ

app/assets/js/app/slidebar.js
スライドメニューのリンクが少ないとき、余白クリックでスライドメニュー自体を閉じるオプション機能の追加
https://www.notion.so/growgroup/158eef14914a803c9b3ef8ca1101a302
包括要素（小要素クリック時は除外）をクリックした際に
bodyTrigger() を発火させてスライドメニューを格納するよう修正
想定HTML構造
```
<div class="c-slidebar-menu  js-slidebar-menu">
<div class="c-slidebar-menu__wrapper js-slidebar-container"> // 利用時追加
<ul class="c-slidebar-menu__list">
・
・
・
```
=> [update]js-slidebar-containerの挙動修正

app/assets/js/app/accordion.js, app/assets/scss/foundation/_mixin.scss, app/assets/scss/layout/footer.scss, app/format/components/_other.pug, app/inc/foundation/_base.pug
改善事項DBより
https://www.notion.so/growgroup/_-DB-f9d56812e4754b0ba5070a7e3d34fce1?p=185eef14914a80878928c18306c2d8ac&pm=s
detailsかそれ以外で判定し可能にしました。
---
PCではリンク、スマホではアコーディオンにする構成のとき、
summaryの内部に a を置くのが若干変なので
（summaryは子にフレージングコンテンツを持てるので、フレージングコンテンツであるaは置けはするが）
従来のHTML構造に近い状態でも動作させられるように変更
=> [update]アコーディオンでタグ違いも可能にする

app/inc/foundation/_base-twocolumn.pug
https://www.notion.so/growgroup/base-twocolumn-l-offer-l-main-1bbeef14914a80c7a0cbcc9e992b7028
2カラムレイアウトのときだけ、l-mainのなかにl-offerが入ってしまっていたのを
1カラムのときと同じ位置に修正。
以下の状態に修正
```
main
<略>
.l-main
.l-two-column
<略>
.l-offer
```
=> base-twocolumnでl-offerがl-mainの中に入っていたのを外に出す

app/assets/js/app/wrapperClasses/micromodalWrapper.js, app/format/components/_modal.pug
https://www.notion.so/growgroup/gg-styleguide-modal-button-1cfeef14914a807ca19cc147d8ae9355
```
+a("https://placehold.jp/300x250.png").c-modal-link.js-modal(data-modal-type="image")
img(src='https://placehold.jp/300x250.png' alt='画像1')
```
```
button.c-modal-link.js-modal(data-modal-type="image" , data-modal-src="https://placehold.jp/300x250.png")
img(src='https://placehold.jp/300x250.png' alt='画像1')
```
=> [update]modal要素をaタグとbuttonタグで動くようにしました

app/assets/js/app/gsap.js, package-lock.json, package.json
https://www.notion.so/growgroup/GSAP-3-12-3-13-MorphSVG-1eceef14914a80ab9127eec13bfe151b
- GSAPのバージョンを 3.12 から 3.13に上げる
- `MorphSVGPlugin` などのimportの例を gsap.js に追加（コメントアウト状態）
https://codepen.io/miral_kashiwagi/pen/oggdWGe
https://gsap.com/blog/3-13/
=> Update GSAP 3.12 -> 3.13

app/assets/scss/object/components/breadcrumb.scss
https://www.notion.so/growgroup/line-clamp-text-overflow-ellipsis-1f3eef14914a809385fdc9071bac2594
https://github.com/growgroup/gg-styleguide/commit/9e4c479c7b26ef3f770e429a368767bfaf0429c9 の修正のロールバック。
iOS18.4とiOS18.5で、https://github.com/growgroup/gg-styleguide/commit/bd028cf5c7d2dfdea96d95c562121b1f0e2371c2 の修正と組み合わせたときに以下の問題が発生していたため。
https://github.com/growgroup/gg-styleguide/commit/bd028cf5c7d2dfdea96d95c562121b1f0e2371c2 の方はiOS17以降でのリンクがタップできない問題の対応で現時点では戻せないので、いったん https://github.com/growgroup/gg-styleguide/commit/9e4c479c7b26ef3f770e429a368767bfaf0429c9 の修正のロールバックで対応
=> [update] c-breadcrumb : line-clamp -> text-overflow :elipsis

config/postcss-var-pxtorem.js, postcss.config.js
https://www.notion.so/growgroup/postcss-pxtorem-var-px-rem-206eef14914a806cab93d9bf5bface92
SCSS側でフォールバック値付きでvar()関数を使うとフォールバック値のpxがrem変換されないため
`postcss-var-pxtorem` を作成して、変換されるように調整しました。
font-size: var(--_card-label-font-size, 13px); ← これが変換されない
---
CSS変数の `var()` 内のフォールバック値のpx単位をrem単位に変換するPostCSSプラグイン
標準の `postcss-pxtorem` プラグインでは、CSS変数のフォールバック値（例：`var(--size, 16px)` の `16px` 部分）は変換されません。このプラグインは、そのような場合にも対応してpx単位をrem単位に変換します。
https://github.com/growgroup/gg-styleguide/blob/4db0e19a302b8c886474c3c19b9c7dcece59ec48/postcss.config.js#L7-L11
| オプション | 型 | デフォルト | 説明 |
|----------|---|-----------|------|
| `rootValue` | number | 16 | ルート要素のフォントサイズ（px）。変換の基準値 |
| `unitPrecision` | number | 5 | rem値の小数点以下の桁数 |
| `minPixelValue` | number | 0 | 変換する最小のpx値。この値未満は変換されない |
| `exclude` | …
=> postcss-var-pxtorem

app/assets/scss/object/components/news-header.scss
news-headerがmarginで実装されており、ラベル、日付等を並び替えた時に毎回調整が必要だったためgapでの実装に変更。
特に見た目上の変更はありません。
▼詳細
c-news-headerのsupをflexのgap実装に変更
https://www.notion.so/growgroup/c-news-header-sup-flex-gap-21feef14914a80398ee0d461bce5b6ef?source=copy_link
=> [edit]news-header marginからgapに変更

app/archive-twocolumns/category/index.pug, app/archive-twocolumns/category/page/index.pug, app/archive-twocolumns/index.pug, app/assets/scss/object/components/card-post.scss, app/news/category/page/index.pug, app/news/index.pug
news/category/page等で実装されていた
.c-card-post内の.row/.large-**/.small-**のクラスを使ったカラムレイアウトをdisplay: gridを使った実装に変更しました。
▼改善事項DB
https://www.notion.so/growgroup/c-card-post-display-grid-auto-fill-114eef14914a80e198a4fd58ee1bfbce?source=copy_link
=> [edit]card-post

app/assets/scss/foundation/_mixin-post-content.scss
業務改善：l-post-content内の要素のmargin-topが見出しのmargin-bottomに勝ってしまう
https://www.notion.so/growgroup/l-post-content-margin-top-margin-bottom-23aeef14914a8015a9c4fde9cbe94a4b
=> [add]l-post-content内の見出し要素のマージンを優先させる

app/assets/js/app/slidebar.js
▼改善事項
https://www.notion.so/growgroup/slidebar-js-activateWidth-253eef14914a808d979eee3fefcc0b15
PCサイズでもハンバーガーメニューボタンを利用するデザインで、activateWidthをnullにし忘れても、
一部の閲覧環境ではハンバーガーメニューが開いてしまう問題
activateWidthが、開くイベントの発火するかどうかにも影響を与えるように変えました。
ハンバーガーメニューボタンを押したとき、開閉イベントは発火していた。
リサイズオブザーバーも発火するので、開閉と同時に閉じるイベントが発火する方向性で作られていたが、
展開時に必ずリサイズオブザーバーが発火するわけではなかったため「普通に開く」環境が存在した。
おそらくMacでスクロールバーを表示しない状態だと、
ハンバーガーメニューボタンを押したときにリサイズオブザーバーが発火していなかった、と予想される。
=> [update] slidebar.js : activateWidthが入っているときに環境によってはナビが開いてしまう問題の修正

app/assets/scss/foundation/_settings.scss, app/assets/scss/object/components/news.scss, app/inc/mixins/_misc.pug, app/news/index.pug, package-lock.json
▼改善事項DB
https://www.notion.so/growgroup/23eeef14914a80d189eacb8210395aa3?source=copy_link
- .c-news__block-icon-fileにmodifierを設定。
- settings.scssにファイル別のカラー変数を設定。
- mixin c_news__blockのロジックを微調整
▼表示は/news/で確認できます。
=> [update]ニュース一覧のファイルアイコン調整

app/contact/index.pug, app/inc/mixins/_misc.pug, package-lock.json
▼改善事項DB
https://www.notion.so/growgroup/mixin-select-ages-for-253eef14914a806bb7d5c4efb0fea2d2?v=3a1267a6dda7402eb247902fd1977c56&source=copy_link
- select-agesをstart,endを指定できるようにして汎用的に。
- 生年月日のselect仕様を/contact/のフォーマットに追加。
- 年、月、日のselectを生成するmixinを追加。name属性も引数で指定可能。
```Pug misc.pug
mixin select-ages(start, end)
select(name="age")
option(disabled,selected) 選択してください
- for (let i = start; i <= end; i++)
<option value="#{i}">#{i}</option>
|　歳
mixin select-year(name="year", startYear=1975, endYear=2007)
select(name=name)
option(disabled,selected) ----
- for (let i = startYear; i <= endYear; i++)
<option value="#{i}">#{i}</option>
//デフォルトは1月から12月
mixin select-month(name="month", start=1, end=12)
select(name=name)
option(disabled,selected) ----
- for (let i = start; i <= end; i++)
<option …
```
=> [update]misc.pug, contact/index.pug 年月日、年齢のselectのmixin調整・強化

app/assets/scss/foundation/_mixin-post-content.scss
▼改善事項
https://www.notion.so/growgroup/l-post-content-l-post-content-where-figure-253eef14914a80469df0caaa09600d58
https://github.com/growgroup/gg-styleguide/pull/216 のあとから
`.l-post-content>*+*`が`.l-post-content :where(figure)`に負けていて、画像の上に余白がつかない
https://github.com/growgroup/gg-styleguide/pull/216 はあくまでHTML時点のCSSのリセットの問題だったのでとりあえず
セレクタを `:where(.l-post-content) figure` に変更しました。
=> .l-post-content>*+*が.l-post-content :where(figure)に負けてる

app/assets/scss/foundation/_mixin-post-content.scss, app/assets/scss/object/components/aside-navs.scss, app/assets/scss/object/components/forms.scss, app/assets/scss/object/components/list.scss, package-lock.json, package.json
▼改善事項
https://www.notion.so/growgroup/lh-23eeef14914a8048956cdf9b4a5945f5
`1em * $font-base-line-height` のように「1行の高さ」を計算していた部分を
`1lh` に置き換えました。
aside-navsのデフォの装飾について、 topで調整しつつさらに transformでも位置を調整していたので、
topのみで調整する形に変更してあります。
iOS16.4からのCSSになるので、
あわせてautoprefixerの対象ブラウザ（browserlist）を `iOS17以下` の設定に変えました。
=> 行の高さを計算している部分をlh単位に置き換える

app/assets/scss/foundation/_mixin.scss
▼改善事項
https://www.notion.so/growgroup/range-syntax-23eeef14914a804ab589f59d3b8419da
以下のmixinを使用したとき、Range syntaxで出力するように変更しました。
- `@include breakepoint(small down)` のようなメディアクエリ
- `@include container(800 down)` のようなコンテナクエリ
Range syntax についての参考： https://zenn.dev/tonkotsuboy_com/articles/css-range-syntax
`@include container(800 down)`のときrem変換で参照している値を修正しました。
mixinの使い方は変更ありません。出力されるCSSだけが変わります。
とくに https://github.com/growgroup/gg-styleguide/pull/160 の修正時に冗長になっていた
以下のようなメディアクエリが1行でかけるようになります
```
@media screen and (max-width: 71.1875em) {
@media not screen and (max-width: 59.3125em) {
}
}
```
```
@media screen and (59.375em <= width < 71.25em){
}
```
厳密には749.5pxの時の挙動が変わっていますが、小数点以下の桁数が少なくて済むように調整しています
=> 比較演算子(Range syntax)の導入
