growgroup/gg-styleguide

app/assets/js/app.js
app/assets/js/app/accordion.js
app/assets/js/app/anchor.js
app/assets/js/app/copyright.js
app/assets/js/app/current-nav.js
app/assets/js/app/custom.js
app/assets/js/app/fixedheader.js
app/assets/js/app/format.js
app/assets/js/app/gsap.js
app/assets/js/app/heightline.js
app/assets/js/app/jquery-shim.js
app/assets/js/app/modal.js
app/assets/js/app/owl-carousel.js
app/assets/js/app/responsive-table.js
app/assets/js/app/scroll-reveal.js
app/assets/js/app/scrollreveal.js
app/assets/js/app/slick-slider.js
app/assets/js/app/slidebar.js
app/assets/js/app/tab.js
app/assets/js/app/utils.js
app/inc/foundation/_head.pug
webpack.config.babel.js

https://a-kobayashi.grgr.blue/test/external-jquery/
https://a-kobayashi.grgr.blue/test/external-jquery/assets/js/app.js

dist/assets/js/app.js のなかにjQueryが入らないようにする・headのjQueryを3.6.0にする

---

app/assets/scss/object/components/_gallery-slider.scss
app/assets/scss/object/components/_grid.scss
app/assets/scss/object/utility/_text.scss
app/inc/mixins/_misc.pug
package-lock.json
package.json

- scripts から消しました
- devDependenciesからも消しました
「歳」の行が謎にエラーを出していたのでとりあえず止めました。
math.div と map.get でphpstormで赤線が入るところを調整しました
以下を追加
```
@use "sass:math";
@use "sass:map";
```
しました。

imagemin消す・scssで赤線はいるところ調整など

---

app/assets/js/app.js
app/assets/js/app/scroll-spy.js

app/assets/js/app/scroll-spy.js に吉岡くんが以前アーバンテラスで書いていたScrollSpy用のjsをclass化しインポートできるようにしました。
(動作未未未未未検証)

Feature/ishihara/20220901 汎用的なScrollSpy用jsを追加

---

app/assets/js/app.js
app/assets/js/app/scroll-table.js
app/format/components/_text.pug
app/inc/foundation/_head.pug
package-lock.json
package.json

scroll-hintをデフォルトで導入しました。
npmからのインストールだと何故か動かなかったので、CDNで読み込んでいます。

scroll-hintの追加(CDN) app/scroll-table.js & head.pug

---

app/assets/js/app/anchor.js
app/assets/js/app/swiper.js
app/assets/scss/foundation/_forms.scss
app/assets/scss/foundation/_normalize.scss
app/assets/scss/layout/_header.scss
app/assets/scss/object/components/_block-document.scss
app/assets/scss/object/components/_buttons.scss
app/assets/scss/object/components/_card-download.scss
app/assets/scss/object/components/_modaal.scss
app/assets/scss/object/components/_relation.scss
app/download/index.pug
app/download/page/index.pug
app/format/components/_buttons.pug
app/format/index.pug
app/inc/mixins/_main-visual.pug
app/inc/mixins/_misc.pug

資料ダウンロードページ一覧と詳細のフォーマット作成

---

app/assets/js/style.js
app/assets/scss/font.scss
app/assets/scss/foundation/_font.scss
app/assets/scss/object/utility/_animate.scss
app/assets/scss/style.scss
webpack.config.babel.js
webpack.style.config.babel.js

cssの文字化け対応

---

app/assets/scss/style.scss

https://www.notion.so/growgroup/2af267d307114d9a8d160e88c9ca4655?v=3a1267a6dda7402eb247902fd1977c56&p=4df6761403d74084b7d7ba1f4adfc4c8&pm=s

style.scss読み込み順番

---

app/assets/scss/layout/_container.scss

.l-containerの調整です。
https://capture.dropbox.com/MCcUIuqC5VjIxkPQ

[add] .l-container

---

app/inc/mixins/_misc.pug

[add] video

---

app/assets/scss/foundation/_mixin.scss
app/assets/scss/object/components/_buttons.scss

hoverをmixin化し、タブレット以下のhoverを切る。
試しにc-buttonのhoverを変えてみました。

[add] mixin hover

---

app/inc/mixins/_accordion.pug

改善事項DB
https://www.notion.so/growgroup/c-accordion-js-accordion-HTML-d27a313bdb1a4be4b49790d579d13ded
以下のコードを毎回非表示にする手間を省く
```pug
// - テンプレート
//  .c-accordion.js-accordion
//   h2.c-accordion__title(data-accordion-title="true")
//     button(aria-controls="accordion-panel-1" aria-expanded="false") title
//   .c-accordion__content(data-accordion-content="true")#accordion-panel-1 text
```
以下、実際のキャプチャ

[update]_accordion.pug

---

.gitignore

以下を追記
```
wp-content/ai1wm-backups/
wp-content/siteguard/*.png
wp-content/siteguard/*.txt
```

[update] gitignore

---

app/assets/js/scripts.js
package-lock.json

こうだったもの（旧）を
```
var loaderFunction = function () {
if ($loader) {
changeClass($loader, "is-active", 1000).then(function () {
changeClass($loader, "is-close", 2000).then(function () {
changeClass($loader, "is-hidden", 1000).then(function () {
});
});
});
}
};
```
以下（新）のように変更
```
var loaderFunction = async function () {
if ($loader) {
await changeClass($loader, "is-active", 1000);
await changeClass($loader, "is-close", 2000);
await changeClass($loader, "is-hidden", 1000);
}
};
```

[update]enterAnimation.js

---

app/privacy-policy/index.pug

▼改善事項
https://www.notion.so/growgroup/gg-styleguide-106eef14914a80e79b1ac5e56d88f863
「※Google Analyticsにおけるデータ取り扱いの詳細はこちらをご確認ください」のリンク貼り漏れ事例が多いため
表のテンプレートを追加
http://localhost:3000/privacy-policy/

[add] privacy-policy

---

app/assets/scss/object/components/pagination.scss

▼改善事項
https://www.notion.so/growgroup/10eeef14914a80baa8d3fce42567abbe
paginationに「スマホ時は「前へ」「次へ」ボタンを削除する」仕様に対応するコードを追加しました。

[update] pagination : スマホ時は「前へ」「次へ」ボタンを削除する 仕様に対応

---

app/assets/scss/object/components/mm.scss

▼改善事項
https://www.notion.so/growgroup/c-mm-CSS-SCSS-__-130eef14914a802d9575c24e0ac6a6e0
https://github.com/growgroup/gg-styleguide/pull/156 で追加したCSSについてSCSSの入れ子が不十分だった問題を修正

[update] c-mm

---

app/format/components/_text.pug
app/inc/mixins/_heading.pug
app/index.pug

https://www.notion.so/growgroup/_-DB-f9d56812e4754b0ba5070a7e3d34fce1?p=153eef14914a802383b7ea1058d330cf&pm=s

heading.pugにタグも引数化

---

app/assets/js/app/scrollable.js
app/assets/scss/object/components/scrollable.scss

詳細と解決策については以下参照
https://www.notion.so/growgroup/scroll-hint-icon-154eef14914a80b4a9c1fba9f63cc3ac

[update]scroll-hintサイズバグ応急処置

---

app/assets/scss/object/components/scrollable.scss
app/format/index.pug

https://www.notion.so/growgroup/scroll-hint-119eef14914a80c088f2fd0867f1e72c

scroll-hintアイコン位置調整

---

app/assets/scss/style.scss
app/inc/mixins/_cssrules.pug
build/pug.js

+prを機能させるために必要なファイルを下記に追加。
参考：https://www.notion.so/growgroup/scss-object-project-a40cc8c2cc474b85a6cab7c09c0d1081
20250116の箇所
assets/scss/objectに「project」フォルダを追加
projectフォルダに_index.scssファイルを追加
▼cssrules.pug
下記を丸ごと追加
**※+pだと、既存の+p（pタグ）と重複するので、pコンポーネントは+prとしています。**
https://github.com/growgroup/gg-styleguide/compare/feature/onishi/20250227?expand=1#diff-b05c646801dacbd5adea2382ed4f1173a504b91ebbd45bae25d971b8f9c5e196R62-R86
▼pug.js
下記の記述に変更
https://github.com/growgroup/gg-styleguide/compare/feature/onishi/20250227?expand=1#diff-96cbcd9206e6e69cb7b2901c9aba8be5748f083d5d10ba812f59f65168830c7eR11-R24
▼style.scss
assets/scss/style.scss
下記の記述を追加
https://github.com/growgroup/gg-styleguide/pull/210/files#diff-bca65a636a7a1fed26f8803980b7e8e3c3d7846354d124c0b28c684989ee2066R40
下記のような流れ
１.+pr.hoge …

+prを機能させるために必要なファイルを一式作成

---

app/assets/js/app/anchor.js
app/assets/scss/object/components/pagetop.scss
app/inc/layout/_footer.pug

改善事項DBより
https://www.notion.so/growgroup/_-DB-f9d56812e4754b0ba5070a7e3d34fce1?p=1f5eef14914a80aa9275ecd9f3f9a8ee&pm=s
---
https://www.digital.go.jp/ (2025.5.19時点)
※ デジタル庁デザインシステムには無い https://design.digital.go.jp/components/scroll-top-button/

pagetopタグ改修

---

app/assets/scss/object/components/forms.scss
app/contact/index.pug

改善DB：フォームのエラー時の挙動を忍ばせておく
https://www.notion.so/growgroup/20deef14914a80658c6ce838985dc21b

[add]CF7用バリデーションアラートCSS

---

app/inc/mixins/_misc.pug

改善事項DBより
https://www.notion.so/growgroup/_-DB-f9d56812e4754b0ba5070a7e3d34fce1?p=209eef14914a802691b8c4c276733b18&pm=s

+pictureの引数を配列からオブジェクトに変更

---

app/format/index.pug
package-lock.json

改善DBより
https://www.notion.so/growgroup/_-DB-f9d56812e4754b0ba5070a7e3d34fce1?p=242eef14914a80c39421e889d90332a8&pm=s

/format/ : ページ内の見出しをh1からh2に変更

---

app/assets/scss/object/components/heading.scss

業務改善
https://www.notion.so/growgroup/c-heading-26aeef14914a8095ba7ac6aa5ba3dc52

[update]c-heading整理
